const navToggle = document.querySelector(".nav-toggle");
const siteNav = document.querySelector(".site-nav");
const languageButtons = document.querySelectorAll("[data-lang]");

const translations = {
  en: {
    topbarText: "AUBMC clinic by appointment",
    topbarAubmc: "+961 (01) 350-000 ext. 5860",
    topbarMobile: "+961 (03) 526-229",
    brandName: "Rida Adel Kassim, MD",
    brandSub: "Hip & Knee Reconstruction",
    navWhen: "When to Visit",
    navSituations: "Your Situation",
    navFirstVisit: "First Visit",
    navCare: "Care",
    navJourney: "Surgery Journey",
    navFaq: "FAQ",
    navAbout: "About",
    navBook: "Book",
    heroEyebrow: "Adult reconstructive surgery in Beirut",
    heroTitle: "Hip and knee replacement care for pain, stiffness, and complex joint problems.",
    heroBody: "Dr. Rida Adel Kassim is an orthopedic surgeon specializing in total hip replacement, total knee replacement, complex hip and knee reconstruction, revision surgery, and infected prosthesis care.",
    heroCta: "Call for appointment",
    heroSecondary: "What to expect",
    doctorName: "Dr. Rida Adel Kassim",
    doctorShort: "Dr. Rida Kassim",
    doctorSub: "MD, Adult Reconstructive Surgery",
    bookingEyebrow: "Appointments",
    bookingTitle: "AUBMC OPD Clinic",
    bookingBody: "American University of Beirut Medical Center, 4th floor, Phase 1, OPD entrance.",
    monday: "Monday",
    wednesday: "Wednesday",
    friday: "Friday",
    hoursFull: "8:00 AM-4:30 PM",
    hoursFriday: "1:00 PM-5:00 PM",
    proof1Label: "Training",
    proof1Title: "AUB + University of Minnesota",
    proof1Body: "Medical school and orthopedic residency at AUB, followed by adult reconstruction fellowship training in the United States.",
    proof2Label: "Special Focus",
    proof2Title: "Complex hip and knee cases",
    proof2Body: "Total joint replacement, revision reconstruction, and infected total joint care.",
    proof3Label: "Academic Work",
    proof3Title: "Publications and book chapters",
    proof3Body: "Peer-reviewed work, teaching, presentations, and outcome projects in hip and knee arthroplasty.",
    situationsEyebrow: "Choose your situation",
    situationsTitle: "Find the path that sounds most like your problem.",
    situationsBody: "Patients usually arrive with one of four concerns. Pick the closest situation, then book a consultation with your imaging and reports.",
    situation1Title: "I have hip arthritis",
    situation1Body: "Hip pain, stiffness, limping, trouble with shoes or socks, and difficulty walking may mean the hip joint needs evaluation.",
    situation2Title: "I have knee arthritis",
    situation2Body: "Knee pain with stairs, standing from a chair, swelling, deformity, or reduced walking distance may need treatment planning.",
    situation3Title: "I already had a replacement",
    situation3Body: "Persistent pain, instability, loosening, wear, or functional decline after a prior implant may require revision assessment.",
    situation4Title: "I may have an infected prosthesis",
    situation4Body: "New pain, wound drainage, fever, swelling, or abnormal blood tests after joint replacement should be reviewed urgently.",
    whenEyebrow: "When to visit",
    whenTitle: "Consider an orthopedic consultation when joint pain starts changing your life.",
    whenBody: "Leading orthopedic centers explain hip and knee replacement around the same patient signs: persistent pain, stiffness, loss of motion, difficulty walking, trouble climbing stairs, and symptoms that no longer respond well to nonsurgical treatment.",
    problem1Title: "Hip or knee arthritis",
    problem1Body: "Osteoarthritis can gradually wear away cartilage, causing pain, stiffness, and limited movement.",
    problem2Title: "Walking and stairs are harder",
    problem2Body: "Patients often seek help when pain affects walking, stairs, getting out of chairs, or daily routines.",
    problem3Title: "Treatment is not enough anymore",
    problem3Body: "Medication, physical therapy, injections, rest, or walking aids may help for a time. Surgery is considered when conservative treatment no longer gives acceptable relief.",
    problem4Title: "Previous implant problem",
    problem4Body: "Revision surgery may be needed for loosening, wear, instability, infection, or persistent pain after a prior joint replacement.",
    firstVisitEyebrow: "Your first visit",
    firstVisitTitle: "Arrive prepared so the consultation can lead to a clear plan.",
    firstVisitBody: "A strong first visit should clarify the diagnosis, review previous treatment, and decide whether the next step is nonsurgical care, more testing, or surgery.",
    bringTitle: "Bring with you",
    bring1: "Recent X-rays, MRI, CT scans, or imaging CDs if available.",
    bring2: "Prior operation reports if you already had joint replacement.",
    bring3: "Medication list, allergies, and medical history.",
    bring4: "Insurance or third-party payer information.",
    expectTitle: "Expect during the visit",
    expect1: "Discussion of pain, function, walking, stairs, and daily limitations.",
    expect2: "Physical exam of strength, movement, stability, and gait.",
    expect3: "Review of imaging and possible request for updated X-rays or labs.",
    expect4: "Treatment options and a practical next-step plan.",
    missingVisitTitle: "Still needed from the practice",
    missingVisitBody: "Placeholder: add expected consultation length, accepted insurance plans, whether Arabic/French/English are spoken, parking/drop-off instructions, and whether patients should book through AUBMC or the office manager.",
    careEyebrow: "Specialized care",
    careTitle: "Care pathways for hip, knee, revision, and infected prosthesis cases.",
    care1Title: "Total Hip Replacement",
    care1Body: "Hip replacement removes damaged bone and cartilage and replaces the joint with prosthetic components. The goal is to reduce pain, improve movement, and make daily activity easier.",
    care2Title: "Total Knee Replacement",
    care2Body: "Knee replacement resurfaces damaged joint surfaces with metal and plastic components. It is considered when severe arthritis or injury limits function and other treatments are no longer enough.",
    care3Title: "Revision and Infected Prosthesis",
    care3Body: "Dr. Kassim takes special interest in complex hip and knee reconstruction, including infected total joints. These cases often require detailed planning, staged treatment, and close follow-up.",
    journeyEyebrow: "Patient journey",
    journeyTitle: "What to expect before surgery, in the hospital, and at home.",
    journeyBody: "This section combines Dr. Kassim's original patient instructions with patient-friendly guidance modeled on major orthopedic hospital resources.",
    step1Title: "First visit and decision",
    step1Body: "Your symptoms, medical history, walking, strength, range of motion, X-rays, and goals are reviewed. The consultation should clarify whether surgery is appropriate now or whether nonsurgical care should continue.",
    step2Title: "Pre-op preparation",
    step2Body: "Testing may include bloodwork, urine testing, chest X-ray, EKG, and anesthesia assessment. You may be asked to stop certain medicines before surgery. Placeholder: add insurance/pre-authorization process.",
    step3Title: "Prepare your home",
    step3Body: "Arrange a walker or cane, a ride home, help with meals and bathing, secure handrails, remove loose rugs, and consider a raised toilet seat or shower chair if recommended.",
    step4Title: "Surgery and hospital stay",
    step4Body: "Hip and knee replacement commonly take around one to two hours, depending on complexity. Dr. Kassim's original instructions describe hospital stay as usually two to four days for his patients.",
    step5Title: "Early movement",
    step5Body: "Breathing exercises, pain control, antibiotics, anticoagulation, wound care, and physical therapy begin early. Walking usually starts with support from a walker or crutches.",
    step6Title: "Recovery at home",
    step6Body: "Follow the therapy plan, keep the wound protected, change dressings as instructed, and progress gradually from walker to cane. Recovery varies; many patients need weeks to months to rebuild strength and confidence.",
    recoveryEyebrow: "Recovery timeline",
    recoveryTitle: "Recovery is gradual. The plan should be clear before you go home.",
    recoveryBody: "Every patient is different, but most people need a structured plan for wound care, walking support, physical therapy, and follow-up.",
    recovery1Label: "Hospital",
    recovery1Title: "First days",
    recovery1Body: "Pain control, breathing exercises, anticoagulation, wound monitoring, and assisted walking begin early.",
    recovery2Label: "Home",
    recovery2Title: "First 2 weeks",
    recovery2Body: "Focus on safe walking, swelling control, keeping the wound protected, and following therapy instructions.",
    recovery3Label: "Follow-up",
    recovery3Title: "Around 3 weeks",
    recovery3Body: "Dr. Kassim's original instructions note suture removal around three weeks, depending on healing and wound status.",
    recovery4Label: "Strength",
    recovery4Title: "6-12 weeks",
    recovery4Body: "Many patients continue building strength, balance, range of motion, and confidence with walking.",
    recoveryPlaceholder: "Placeholder: add Dr. Kassim's exact follow-up schedule, physical therapy protocol, driving guidance, return-to-work guidance, and downloadable wound-care handout.",
    safetyEyebrow: "Safety and recovery",
    safetyTitle: "Clear instructions matter after joint replacement.",
    safety1Title: "Call the clinic for",
    safety1Body: "Wound drainage, increasing redness, unusual soreness, significant leg swelling, difficulty breathing, fever, or sudden worsening pain.",
    safety2Title: "Hip precautions",
    safety2Body: "Depending on the surgical approach, patients may be told not to cross the legs, bend the hip too far, twist, or sit on low chairs during early recovery.",
    safety3Title: "Activity expectations",
    safety3Body: "Low-impact activities are usually preferred after recovery. High-impact activity should be discussed directly with the surgeon.",
    aboutEyebrow: "About Dr. Kassim",
    aboutTitle: "Fellowship-trained adult reconstructive orthopedic surgeon.",
    aboutBody1: "Dr. Kassim completed undergraduate studies, medical school training, and orthopedic residency at the American University of Beirut. He then completed a fellowship in adult reconstructive surgery at the University of Minnesota in the United States.",
    aboutBody2: "He has published peer-reviewed articles, contributed book chapters, presented nationally and internationally, and participated in hip and knee outcome projects. His main interest is complex hip and knee reconstruction with special emphasis on infected total joints.",
    staffTitle: "Office Manager",
    staffName: "Alia Barki",
    staffPlaceholder: "Placeholder: add WhatsApp number or preferred appointment workflow if applicable.",
    faqEyebrow: "Questions patients ask",
    faqTitle: "Practical answers before you book.",
    faq1Q: "Will I be pain free after surgery?",
    faq1A: "The goal is meaningful pain reduction and better function. Some discomfort is expected during recovery, and every patient heals differently.",
    faq2Q: "How soon do I walk after surgery?",
    faq2A: "Walking usually begins early with assistance from the care team and a walker or crutches. Physical therapy guides safe progress.",
    faq3Q: "How long is the hospital stay?",
    faq3A: "Dr. Kassim's original guidance describes a typical stay of two to four days, depending on the surgery and recovery.",
    faq4Q: "Do I need a rehabilitation facility?",
    faq4A: "The original FAQ says most patients go home with scheduled physiotherapy visits, but the final plan depends on safety, mobility, and medical condition.",
    faq5Q: "What information is missing from this website?",
    faq5A: "Placeholder: add accepted insurance, exact parking/drop-off instructions, whether WhatsApp booking is available, languages spoken, emergency after-hours instructions, and downloadable pre-op forms.",
    originalFaqEyebrow: "Original FAQ",
    originalFaqTitle: "Detailed questions from the previous website.",
    originalFaqBody: "These are the original patient questions and answers, reorganized into a cleaner format.",
    oldFaq1Q: "Is joint replacement the best treatment for me right now?",
    oldFaq1A: "Please refer to the Surgery Journey section and discuss nonsurgical and surgical options during consultation.",
    oldFaq2Q: "How well does surgery work for someone my age and medical condition?",
    oldFaq2A: "Surgery can work well, but the plan depends on your age, medical problems, diagnosis, and readiness for surgery.",
    oldFaq3Q: "Will I be able to walk without pain?",
    oldFaq3A: "The original FAQ states that patients should be able to walk freely with minimal pain, but not necessarily pain free.",
    oldFaq4Q: "Will I be able to do activities such as golf, swimming, tennis, or hiking?",
    oldFaq4A: "The original FAQ says some activities may be considered around six months after surgery, although hiking is not advised.",
    oldFaq5Q: "What can I do before surgery to help the result?",
    oldFaq5A: "Read and follow the surgery preparation instructions. Exercises, learning to use a walker or crutches, stopping smoking and alcohol, and bathing the night before surgery may help reduce risk.",
    oldFaq6Q: "Do I need to lose weight before surgery?",
    oldFaq6A: "The original FAQ says weight loss is not always required, but it can help.",
    oldFaq7Q: "How much help will I need when I come home?",
    oldFaq7A: "The original FAQ says patients should be able to get to the bathroom by themselves on discharge, but help at home is still useful, especially for showering and safety.",
    oldFaq8Q: "How can I make my home safer?",
    oldFaq8A: "Avoid slippery floors and shoes. Use recommended aids such as a walker, cane, and raised toilet seat after hip replacement if instructed.",
    oldFaq9Q: "Do I need a hospital bed or rehabilitation facility?",
    oldFaq9A: "The original FAQ says a hospital bed is usually not needed unless requested by the physician, and most patients do not need a rehabilitation facility; physiotherapy visits are scheduled.",
    oldFaq10Q: "What are the risks or complications?",
    oldFaq10A: "Risks discussed on the previous site include infection, deep vein thrombosis, neurovascular injury, and anesthesia-related risks.",
    oldFaq11Q: "Will I need a blood transfusion?",
    oldFaq11A: "The original FAQ says auto-transfusion is not used and patients should contact the blood bank to arrange blood when asked.",
    oldFaq12Q: "How long will surgery and hospital stay last?",
    oldFaq12A: "The original FAQ describes primary surgery as around one hour and thirty minutes, revision surgery as around three hours, and hospital stay as two to four days.",
    oldFaq13Q: "What type of anesthesia will be used?",
    oldFaq13A: "Anesthesia choices are discussed with the anesthesiologist.",
    oldFaq14Q: "Will I have pain after surgery?",
    oldFaq14A: "Some pain is expected after surgery. Pain medications are provided as part of recovery.",
    oldFaq15Q: "How soon will I get up and move?",
    oldFaq15A: "The original FAQ says patients usually get up and move around on the second day after surgery, with physical therapy in the hospital.",
    oldFaq16Q: "Will I go home walking?",
    oldFaq16A: "The original FAQ says patients go home ambulatory, and total hip surgery patients are discharged home with an ambulance.",
    oldFaq17Q: "Do I need to stop medicines before surgery?",
    oldFaq17A: "Yes. Anticoagulation and some other medicines may need to be stopped. The nurse manager should be consulted when scheduling the case.",
    bookingStepsEyebrow: "How to become a patient",
    bookingStepsTitle: "The booking process should be simple and visible.",
    bookingStepsBody: "Use the current clinic numbers below. Missing operational details are highlighted so they can be completed by the practice.",
    bookStep1Title: "Call or email",
    bookStep1Body: "Call AUBMC ext. 5860, call +961 (03) 526-229, or email rk244@aub.edu.lb.",
    bookStep2Title: "Confirm clinic day",
    bookStep2Body: "Clinic hours listed on the source site are Monday and Wednesday 8:00 AM-4:30 PM, and Friday 1:00 PM-5:00 PM.",
    bookStep3Title: "Prepare your records",
    bookStep3Body: "Bring imaging, prior reports, medication list, medical conditions, and insurance information.",
    bookStep4Title: "Missing workflow",
    bookStep4Body: "Placeholder: confirm whether patients should call AUBMC first, call Alia first, use WhatsApp, or use an online hospital appointment system.",
    contactEyebrow: "Book an appointment",
    contactTitle: "AUBMC clinic, by appointment.",
    contactBody: "Clinic venue: American University of Beirut Medical Center, 4th floor, Phase 1, OPD entrance.",
    contactCall: "Call +961 (03) 526-229",
    contactEmail: "Email clinic",
    scheduleTitle: "Clinic Hours",
    labelAubmc: "AUBMC:",
    labelMobile: "Mobile:",
    labelEmail: "Email:",
    labelLinkedin: "LinkedIn:",
    labelFacebook: "Facebook:",
    locationsTitle: "Practice locations",
    loc1Title: "AUBMC",
    loc1Body: "4th floor, Phase 1, OPD entrance",
    loc2Title: "Sahel General Hospital",
    loc2Body: "Ghobeiri, Beirut, Lebanon",
    loc3Title: "Clemenceau Medical Center",
    loc3Body: "Hamra, Beirut, Lebanon",
    loc4Title: "Rafik Hariri University Hospital",
    loc4Body: "Jnah, Beirut, Lebanon",
    loc5Title: "Bahman Hospital",
    loc5Body: "Haret Hreik, Beirut, Lebanon",
    footerText: "Rida Adel Kassim, MD | Adult Reconstructive Hip & Knee Surgery",
    backTop: "Back to top"
  },
  fr: {
    topbarText: "Clinique AUBMC sur rendez-vous",
    topbarAubmc: "+961 (01) 350-000 poste 5860",
    topbarMobile: "+961 (03) 526-229",
    brandName: "Dr Rida Adel Kassim",
    brandSub: "Reconstruction hanche et genou",
    navWhen: "Quand consulter",
    navSituations: "Votre situation",
    navFirstVisit: "Premiere visite",
    navCare: "Soins",
    navJourney: "Parcours chirurgical",
    navFaq: "FAQ",
    navAbout: "A propos",
    navBook: "Rendez-vous",
    heroEyebrow: "Chirurgie reconstructive de l'adulte a Beyrouth",
    heroTitle: "Soins de remplacement de la hanche et du genou pour la douleur, la raideur et les cas complexes.",
    heroBody: "Le Dr Rida Adel Kassim est chirurgien orthopediste specialise dans le remplacement total de la hanche, le remplacement total du genou, la reconstruction complexe de la hanche et du genou, la chirurgie de revision et la prise en charge des protheses infectees.",
    heroCta: "Appeler pour rendez-vous",
    heroSecondary: "A quoi s'attendre",
    doctorName: "Dr Rida Adel Kassim",
    doctorShort: "Dr Rida Kassim",
    doctorSub: "MD, chirurgie reconstructive de l'adulte",
    bookingEyebrow: "Rendez-vous",
    bookingTitle: "Clinique externe AUBMC",
    bookingBody: "American University of Beirut Medical Center, 4e etage, Phase 1, entree des consultations externes.",
    monday: "Lundi",
    wednesday: "Mercredi",
    friday: "Vendredi",
    hoursFull: "8h00 - 16h30",
    hoursFriday: "13h00 - 17h00",
    proof1Label: "Formation",
    proof1Title: "AUB + University of Minnesota",
    proof1Body: "Etudes medicales et residence en orthopedie a l'AUB, puis fellowship en reconstruction de l'adulte aux Etats-Unis.",
    proof2Label: "Specialisation",
    proof2Title: "Cas complexes de hanche et de genou",
    proof2Body: "Remplacement articulaire, reconstruction de revision et prise en charge des protheses infectees.",
    proof3Label: "Travail academique",
    proof3Title: "Publications et chapitres de livres",
    proof3Body: "Travaux revus par les pairs, enseignement, presentations et projets de resultats en arthroplastie de la hanche et du genou.",
    situationsEyebrow: "Choisissez votre situation",
    situationsTitle: "Trouvez le parcours qui ressemble le plus a votre probleme.",
    situationsBody: "Les patients arrivent generalement avec l'une de quatre preoccupations. Choisissez la situation la plus proche, puis prenez rendez-vous avec vos images et rapports.",
    situation1Title: "J'ai une arthrose de la hanche",
    situation1Body: "Douleur de hanche, raideur, boiterie, difficulte a mettre chaussures ou chaussettes, et difficulte a marcher peuvent necessiter une evaluation.",
    situation2Title: "J'ai une arthrose du genou",
    situation2Body: "Douleur au genou dans les escaliers, en se levant d'une chaise, gonflement, deformation ou reduction de la distance de marche peuvent necessiter une planification du traitement.",
    situation3Title: "J'ai deja une prothese",
    situation3Body: "Douleur persistante, instabilite, descellement, usure ou baisse de fonction apres une prothese peuvent necessiter une evaluation de revision.",
    situation4Title: "Ma prothese pourrait etre infectee",
    situation4Body: "Nouvelle douleur, ecoulement de la plaie, fievre, gonflement ou analyses sanguines anormales apres un remplacement articulaire doivent etre revus rapidement.",
    whenEyebrow: "Quand consulter",
    whenTitle: "Envisagez une consultation orthopedique quand la douleur articulaire commence a changer votre vie.",
    whenBody: "Les grands centres orthopediques decrivent le remplacement de la hanche et du genou autour des memes signes: douleur persistante, raideur, perte de mobilite, difficulte a marcher, difficulte dans les escaliers et symptomes qui ne repondent plus suffisamment aux traitements non chirurgicaux.",
    problem1Title: "Arthrose de hanche ou de genou",
    problem1Body: "L'arthrose peut user progressivement le cartilage, causant douleur, raideur et limitation du mouvement.",
    problem2Title: "Marcher et monter les escaliers devient plus difficile",
    problem2Body: "Les patients consultent souvent lorsque la douleur affecte la marche, les escaliers, le lever d'une chaise ou les activites quotidiennes.",
    problem3Title: "Le traitement ne suffit plus",
    problem3Body: "Medicaments, physiotherapie, injections, repos ou aides a la marche peuvent aider un temps. La chirurgie est envisagee lorsque le traitement conservateur n'apporte plus un soulagement acceptable.",
    problem4Title: "Probleme avec une prothese anterieure",
    problem4Body: "Une chirurgie de revision peut etre necessaire en cas de descellement, usure, instabilite, infection ou douleur persistante apres une prothese.",
    firstVisitEyebrow: "Votre premiere visite",
    firstVisitTitle: "Arrivez prepare afin que la consultation mene a un plan clair.",
    firstVisitBody: "Une premiere visite efficace doit clarifier le diagnostic, revoir les traitements deja essayes et decider si la prochaine etape est un traitement non chirurgical, des examens supplementaires ou une chirurgie.",
    bringTitle: "A apporter",
    bring1: "Radiographies recentes, IRM, scanner ou CD d'imagerie si disponibles.",
    bring2: "Comptes rendus operatoires precedents si vous avez deja une prothese.",
    bring3: "Liste des medicaments, allergies et antecedents medicaux.",
    bring4: "Informations d'assurance ou de tiers payant.",
    expectTitle: "Pendant la visite",
    expect1: "Discussion de la douleur, de la fonction, de la marche, des escaliers et des limites quotidiennes.",
    expect2: "Examen de la force, du mouvement, de la stabilite et de la marche.",
    expect3: "Revue des images et demande possible de radiographies ou analyses recentes.",
    expect4: "Options de traitement et plan pratique pour la prochaine etape.",
    missingVisitTitle: "Informations encore necessaires de la clinique",
    missingVisitBody: "Placeholder: ajouter la duree prevue de la consultation, les assurances acceptees, les langues parlees arabe/francais/anglais, les instructions parking/depose-minute, et si les patients doivent reserver via AUBMC ou via la responsable du bureau.",
    careEyebrow: "Soins specialises",
    careTitle: "Parcours de soins pour la hanche, le genou, les revisions et les protheses infectees.",
    care1Title: "Remplacement total de la hanche",
    care1Body: "Le remplacement de la hanche retire l'os et le cartilage abimes et remplace l'articulation par des composants prothetiques. L'objectif est de reduire la douleur, ameliorer le mouvement et faciliter les activites quotidiennes.",
    care2Title: "Remplacement total du genou",
    care2Body: "Le remplacement du genou remplace les surfaces articulaires abimees avec des composants metalliques et plastiques. Il est envisage lorsque l'arthrose severe ou une blessure limite la fonction et que les autres traitements ne suffisent plus.",
    care3Title: "Revision et prothese infectee",
    care3Body: "Le Dr Kassim porte un interet particulier a la reconstruction complexe de la hanche et du genou, y compris les protheses infectees. Ces cas demandent souvent une planification detaillee, un traitement par etapes et un suivi rapproche.",
    journeyEyebrow: "Parcours du patient",
    journeyTitle: "A quoi s'attendre avant la chirurgie, a l'hopital et a domicile.",
    journeyBody: "Cette section combine les consignes originales du Dr Kassim avec des informations plus accessibles inspirees des grandes ressources hospitalieres en orthopedie.",
    step1Title: "Premiere visite et decision",
    step1Body: "Vos symptomes, antecedents, marche, force, amplitude de mouvement, radiographies et objectifs sont revus. La consultation doit clarifier si la chirurgie est indiquee maintenant ou si les soins non chirurgicaux doivent continuer.",
    step2Title: "Preparation preoperatoire",
    step2Body: "Les examens peuvent inclure analyses sanguines, urine, radiographie du thorax, ECG et evaluation d'anesthesie. Certains medicaments peuvent devoir etre arretes avant la chirurgie. Placeholder: ajouter le processus d'assurance/pre-autorisation.",
    step3Title: "Preparer la maison",
    step3Body: "Prevoyez marchette ou canne, transport de retour, aide pour repas et douche, mains courantes securisees, retrait des tapis mobiles et siege sureleve ou chaise de douche si recommande.",
    step4Title: "Chirurgie et sejour hospitalier",
    step4Body: "Le remplacement de hanche ou de genou dure souvent environ une a deux heures selon la complexite. Les consignes originales du Dr Kassim decrivent un sejour habituel de deux a quatre jours.",
    step5Title: "Mouvement precoce",
    step5Body: "Exercices respiratoires, controle de la douleur, antibiotiques, anticoagulation, soins de plaie et physiotherapie commencent tot. La marche debute souvent avec marchette ou bequilles.",
    step6Title: "Recuperation a domicile",
    step6Body: "Suivez le plan de physiotherapie, protegez la plaie, changez les pansements comme indique et progressez graduellement de la marchette a la canne. La recuperation varie et peut prendre des semaines a des mois.",
    recoveryEyebrow: "Calendrier de recuperation",
    recoveryTitle: "La recuperation est progressive. Le plan doit etre clair avant le retour a domicile.",
    recoveryBody: "Chaque patient est different, mais la plupart ont besoin d'un plan structure pour les soins de plaie, l'aide a la marche, la physiotherapie et le suivi.",
    recovery1Label: "Hopital",
    recovery1Title: "Premiers jours",
    recovery1Body: "Controle de la douleur, exercices respiratoires, anticoagulation, surveillance de la plaie et marche assistee commencent tot.",
    recovery2Label: "Domicile",
    recovery2Title: "Deux premieres semaines",
    recovery2Body: "L'objectif est de marcher en securite, controler le gonflement, proteger la plaie et suivre les consignes de physiotherapie.",
    recovery3Label: "Suivi",
    recovery3Title: "Environ 3 semaines",
    recovery3Body: "Les consignes originales du Dr Kassim mentionnent le retrait des sutures vers trois semaines, selon la cicatrisation.",
    recovery4Label: "Force",
    recovery4Title: "6-12 semaines",
    recovery4Body: "Beaucoup de patients continuent a renforcer force, equilibre, amplitude de mouvement et confiance a la marche.",
    recoveryPlaceholder: "Placeholder: ajouter le calendrier exact de suivi du Dr Kassim, le protocole de physiotherapie, les consignes de conduite, le retour au travail et une fiche telechargeable de soins de plaie.",
    safetyEyebrow: "Securite et recuperation",
    safetyTitle: "Des consignes claires comptent apres un remplacement articulaire.",
    safety1Title: "Appelez la clinique en cas de",
    safety1Body: "Ecoulement de la plaie, rougeur croissante, douleur inhabituelle, gonflement important de la jambe, difficulte a respirer, fievre ou aggravation soudaine de la douleur.",
    safety2Title: "Precautions pour la hanche",
    safety2Body: "Selon l'approche chirurgicale, il peut etre demande d'eviter de croiser les jambes, trop flechir la hanche, tourner excessivement ou s'asseoir sur des sieges bas au debut.",
    safety3Title: "Activite attendue",
    safety3Body: "Les activites a faible impact sont generalement preferees apres recuperation. Les activites a fort impact doivent etre discutees directement avec le chirurgien.",
    aboutEyebrow: "A propos du Dr Kassim",
    aboutTitle: "Chirurgien orthopediste forme par fellowship en reconstruction de l'adulte.",
    aboutBody1: "Le Dr Kassim a complete ses etudes universitaires, sa formation medicale et sa residence en orthopedie a l'American University of Beirut. Il a ensuite complete un fellowship en chirurgie reconstructive de l'adulte a l'University of Minnesota aux Etats-Unis.",
    aboutBody2: "Il a publie des articles revus par les pairs, contribue a des chapitres de livres, presente au niveau national et international, et participe a des projets de resultats sur la hanche et le genou. Son interet principal est la reconstruction complexe de la hanche et du genou, avec un accent particulier sur les protheses infectees.",
    staffTitle: "Responsable du bureau",
    staffName: "Alia Barki",
    staffPlaceholder: "Placeholder: ajouter le numero WhatsApp ou le mode de prise de rendez-vous prefere si applicable.",
    faqEyebrow: "Questions frequentes",
    faqTitle: "Reponses pratiques avant de reserver.",
    faq1Q: "Serai-je sans douleur apres la chirurgie ?",
    faq1A: "L'objectif est une reduction importante de la douleur et une meilleure fonction. Un certain inconfort est attendu pendant la recuperation, et chaque patient guerit differemment.",
    faq2Q: "Quand vais-je marcher apres la chirurgie ?",
    faq2A: "La marche commence generalement tot avec l'aide de l'equipe et une marchette ou des bequilles. La physiotherapie guide la progression en securite.",
    faq3Q: "Combien de temps dure le sejour a l'hopital ?",
    faq3A: "Les consignes originales du Dr Kassim decrivent un sejour typique de deux a quatre jours, selon la chirurgie et la recuperation.",
    faq4Q: "Ai-je besoin d'un centre de rehabilitation ?",
    faq4A: "La FAQ originale indique que la plupart des patients rentrent a domicile avec des visites programmees de physiotherapie, mais le plan final depend de la securite, de la mobilite et de l'etat medical.",
    faq5Q: "Quelles informations manquent sur ce site ?",
    faq5A: "Placeholder: ajouter les assurances acceptees, les instructions parking/depose-minute, la disponibilite de WhatsApp, les langues parlees, les consignes d'urgence hors horaires et les formulaires preoperatoires telechargeables.",
    originalFaqEyebrow: "FAQ originale",
    originalFaqTitle: "Questions detaillees de l'ancien site.",
    originalFaqBody: "Ces questions et reponses viennent de l'ancien site et sont reorganisees dans un format plus clair.",
    oldFaq1Q: "Le remplacement articulaire est-il le meilleur traitement pour moi maintenant ?",
    oldFaq1A: "Veuillez consulter la section d'education du patient et discuter des options non chirurgicales et chirurgicales pendant la consultation.",
    oldFaq2Q: "La chirurgie fonctionne-t-elle bien a mon age et avec mes problemes medicaux ?",
    oldFaq2A: "La chirurgie peut bien fonctionner, mais le plan depend de l'age, des problemes medicaux, du diagnostic et de la preparation a la chirurgie.",
    oldFaq3Q: "Pourrai-je marcher sans douleur ?",
    oldFaq3A: "La FAQ originale indique que les patients devraient pouvoir marcher librement avec une douleur minimale, mais pas forcement sans aucune douleur.",
    oldFaq4Q: "Pourrai-je reprendre des activites comme golf, natation, tennis ou randonnee ?",
    oldFaq4A: "La FAQ originale indique que certaines activites peuvent etre envisagees vers six mois apres la chirurgie, mais la randonnee n'est pas conseillee.",
    oldFaq5Q: "Que puis-je faire avant la chirurgie pour aider le resultat ?",
    oldFaq5A: "Lisez et suivez les consignes d'education du patient. Les exercices, apprendre a utiliser une marchette ou des bequilles, arreter tabac et alcool, et se laver la veille peuvent aider a reduire les risques.",
    oldFaq6Q: "Dois-je perdre du poids avant la chirurgie ?",
    oldFaq6A: "La FAQ originale indique que ce n'est pas toujours obligatoire, mais que cela peut aider.",
    oldFaq7Q: "De quelle aide aurai-je besoin en rentrant chez moi ?",
    oldFaq7A: "La FAQ originale indique que les patients devraient pouvoir aller seuls aux toilettes a la sortie, mais l'aide a domicile reste utile, surtout pour la douche et la securite.",
    oldFaq8Q: "Comment rendre ma maison plus sure ?",
    oldFaq8A: "Evitez les sols et chaussures glissants. Utilisez les aides recommandees comme marchette, canne et siege de toilette sureleve apres une prothese de hanche si indique.",
    oldFaq9Q: "Ai-je besoin d'un lit d'hopital ou d'un centre de rehabilitation ?",
    oldFaq9A: "La FAQ originale indique qu'un lit d'hopital n'est generalement pas necessaire sauf demande du medecin, et que la plupart des patients n'ont pas besoin d'un centre de rehabilitation; des visites de physiotherapie sont programmees.",
    oldFaq10Q: "Quels sont les risques ou complications ?",
    oldFaq10A: "Les risques mentionnes sur l'ancien site incluent infection, thrombose veineuse profonde, lesion neurovasculaire et risques lies a l'anesthesie.",
    oldFaq11Q: "Aurai-je besoin d'une transfusion sanguine ?",
    oldFaq11A: "La FAQ originale indique que l'auto-transfusion n'est pas utilisee et que les patients doivent contacter la banque du sang lorsqu'on le leur demande.",
    oldFaq12Q: "Combien de temps durent la chirurgie et le sejour hospitalier ?",
    oldFaq12A: "La FAQ originale decrit une chirurgie primaire d'environ une heure et trente minutes, une revision d'environ trois heures, et un sejour de deux a quatre jours.",
    oldFaq13Q: "Quel type d'anesthesie sera utilise ?",
    oldFaq13A: "Les choix d'anesthesie sont discutes avec l'anesthesiologiste.",
    oldFaq14Q: "Aurai-je mal apres la chirurgie ?",
    oldFaq14A: "Une certaine douleur est attendue apres la chirurgie. Des medicaments antidouleur font partie de la recuperation.",
    oldFaq15Q: "Quand vais-je me lever et bouger ?",
    oldFaq15A: "La FAQ originale indique que les patients se levent et bougent generalement le deuxieme jour apres la chirurgie, avec physiotherapie a l'hopital.",
    oldFaq16Q: "Vais-je rentrer chez moi en marchant ?",
    oldFaq16A: "La FAQ originale indique que les patients rentrent chez eux en marchant, et que les patients ayant une chirurgie de hanche sortent en ambulance.",
    oldFaq17Q: "Dois-je arreter des medicaments avant la chirurgie ?",
    oldFaq17A: "Oui. Les anticoagulants et certains autres medicaments peuvent devoir etre arretes. La responsable infirmiere doit etre consultee lors de la programmation du cas.",
    bookingStepsEyebrow: "Comment devenir patient",
    bookingStepsTitle: "Le processus de rendez-vous doit etre simple et visible.",
    bookingStepsBody: "Utilisez les numeros actuels ci-dessous. Les details operationnels manquants sont surlignes pour etre completes par la pratique.",
    bookStep1Title: "Appeler ou envoyer un email",
    bookStep1Body: "Appelez AUBMC poste 5860, appelez +961 (03) 526-229, ou ecrivez a rk244@aub.edu.lb.",
    bookStep2Title: "Confirmer le jour de clinique",
    bookStep2Body: "Les horaires indiques sur le site source sont lundi et mercredi 8h00-16h30, et vendredi 13h00-17h00.",
    bookStep3Title: "Preparer vos documents",
    bookStep3Body: "Apportez les images, rapports precedents, liste de medicaments, problemes medicaux et informations d'assurance.",
    bookStep4Title: "Parcours de reservation manquant",
    bookStep4Body: "Placeholder: confirmer si les patients doivent appeler AUBMC d'abord, appeler Alia d'abord, utiliser WhatsApp ou utiliser un systeme de rendez-vous hospitalier en ligne.",
    contactEyebrow: "Prendre rendez-vous",
    contactTitle: "Clinique AUBMC, sur rendez-vous.",
    contactBody: "Lieu de consultation: American University of Beirut Medical Center, 4e etage, Phase 1, entree des consultations externes.",
    contactCall: "Appeler +961 (03) 526-229",
    contactEmail: "Envoyer un email",
    scheduleTitle: "Horaires de clinique",
    labelAubmc: "AUBMC:",
    labelMobile: "Mobile:",
    labelEmail: "Email:",
    labelLinkedin: "LinkedIn:",
    labelFacebook: "Facebook:",
    locationsTitle: "Lieux de consultation",
    loc1Title: "AUBMC",
    loc1Body: "4e etage, Phase 1, entree des consultations externes",
    loc2Title: "Sahel General Hospital",
    loc2Body: "Ghobeiri, Beyrouth, Liban",
    loc3Title: "Clemenceau Medical Center",
    loc3Body: "Hamra, Beyrouth, Liban",
    loc4Title: "Rafik Hariri University Hospital",
    loc4Body: "Jnah, Beyrouth, Liban",
    loc5Title: "Bahman Hospital",
    loc5Body: "Haret Hreik, Beyrouth, Liban",
    footerText: "Dr Rida Adel Kassim | Chirurgie reconstructive de la hanche et du genou",
    backTop: "Retour en haut"
  },
  hy: {
    topbarText: "AUBMC կլինիկա՝ միայն ժամադրությամբ",
    topbarAubmc: "+961 (01) 350-000 x 5860",
    topbarMobile: "+961 (03) 526-229",
    brandName: "Դր. Ռիդա Ադել Կասիմ",
    brandSub: "Կոնքի եւ ծնկի վերականգնում",
    navWhen: "Երբ դիմել",
    navSituations: "Ձեր վիճակը",
    navFirstVisit: "Առաջին այց",
    navCare: "Բուժում",
    navJourney: "Վիրահատության ընթացք",
    navFaq: "FAQ",
    navAbout: "Բժշկի մասին",
    navBook: "Ժամադրություն",
    heroEyebrow: "Մեծահասակների վերականգնողական վիրաբուժություն Բեյրութում",
    heroTitle: "Կոնքի եւ ծնկի փոխարինման խնամք՝ ցավի, կոշտության եւ բարդ հոդային խնդիրների համար։",
    heroBody: "Դր. Ռիդա Ադել Կասիմը օրթոպեդ վիրաբույժ է, մասնագիտացած կոնքի ամբողջական փոխարինման, ծնկի ամբողջական փոխարինման, կոնքի եւ ծնկի բարդ վերականգնման, վերավիրահատության եւ վարակված պրոթեզների խնամքի մեջ։",
    heroCta: "Զանգահարել ժամադրության համար",
    heroSecondary: "Ինչ սպասել",
    doctorName: "Դր. Ռիդա Ադել Կասիմ",
    doctorShort: "Դր. Ռիդա Կասիմ",
    doctorSub: "Բժիշկ, մեծահասակների վերականգնողական վիրաբուժություն",
    bookingEyebrow: "Ժամադրություններ",
    bookingTitle: "AUBMC արտաքին կլինիկա",
    bookingBody: "Ամերիկյան համալսարանի բժշկական կենտրոն Բեյրութում, 4-րդ հարկ, Phase 1, արտաքին կլինիկայի մուտք։",
    monday: "Երկուշաբթի",
    wednesday: "Չորեքշաբթի",
    friday: "Ուրբաթ",
    hoursFull: "8:00 - 16:30",
    hoursFriday: "13:00 - 17:00",
    proof1Label: "Ուսուցում",
    proof1Title: "AUB + University of Minnesota",
    proof1Body: "Բժշկական կրթություն եւ օրթոպեդիայի ռեզիդենտուրա AUB-ում, ապա մեծահասակների վերականգնողական վիրաբուժության ֆելոուշիփ ԱՄՆ-ում։",
    proof2Label: "Հատուկ ուղղություն",
    proof2Title: "Կոնքի եւ ծնկի բարդ դեպքեր",
    proof2Body: "Հոդի փոխարինում, վերավիրահատական վերականգնում եւ վարակված հոդային պրոթեզների խնամք։",
    proof3Label: "Գիտական աշխատանք",
    proof3Title: "Հրապարակումներ եւ գրքի գլուխներ",
    proof3Body: "Գրախոսված աշխատանքներ, դասավանդում, զեկույցներ եւ կոնքի ու ծնկի արթրոպլաստիկայի արդյունքների նախագծեր։",
    situationsEyebrow: "Ընտրեք ձեր վիճակը",
    situationsTitle: "Գտեք այն ուղին, որը ամենից շատ նման է ձեր խնդրին։",
    situationsBody: "Հիվանդները սովորաբար դիմում են չորս հիմնական մտահոգություններից մեկով։ Ընտրեք ամենամոտ իրավիճակը, ապա ամրագրեք խորհրդատվություն՝ բերելով ձեր նկարներն ու հաշվետվությունները։",
    situation1Title: "Ես ունեմ կոնքի արթրոզ",
    situation1Body: "Կոնքի ցավը, կոշտությունը, կաղալը, կոշիկ կամ գուլպա հագնելու դժվարությունը եւ քայլելու դժվարությունը կարող են նշանակել, որ կոնքի հոդը պետք է գնահատվի։",
    situation2Title: "Ես ունեմ ծնկի արթրոզ",
    situation2Body: "Ծնկի ցավը աստիճանների ժամանակ, աթոռից վեր կենալիս, այտուցը, դեֆորմացիան կամ քայլելու տարածության նվազումը կարող են պահանջել բուժման պլանավորում։",
    situation3Title: "Ես արդեն ունեմ հոդի պրոթեզ",
    situation3Body: "Նախկին իմպլանտից հետո շարունակվող ցավը, անկայունությունը, թուլացումը, մաշվածությունը կամ ֆունկցիայի վատացումը կարող են պահանջել վերավիրահատության գնահատում։",
    situation4Title: "Իմ պրոթեզը կարող է վարակված լինել",
    situation4Body: "Հոդի փոխարինումից հետո նոր ցավը, վերքի արտադրությունը, ջերմությունը, այտուցը կամ աննորմալ արյան քննությունները պետք է արագ գնահատվեն։",
    whenEyebrow: "Երբ դիմել",
    whenTitle: "Մտածեք օրթոպեդի խորհրդատվության մասին, երբ հոդի ցավը սկսում է փոխել ձեր կյանքը։",
    whenBody: "Առաջատար օրթոպեդիկ կենտրոնները կոնքի եւ ծնկի փոխարինումը բացատրում են նույն նշաններով՝ շարունակական ցավ, կոշտություն, շարժման կորուստ, քայլելու դժվարություն, աստիճան բարձրանալու դժվարություն եւ ախտանիշներ, որոնք այլեւս բավարար չեն արձագանքում ոչ վիրահատական բուժմանը։",
    problem1Title: "Կոնքի կամ ծնկի արթրոզ",
    problem1Body: "Արթրոզը կարող է աստիճանաբար մաշեցնել աճառը՝ առաջացնելով ցավ, կոշտություն եւ շարժման սահմանափակում։",
    problem2Title: "Քայլելն ու աստիճան բարձրանալը դժվարացել են",
    problem2Body: "Հիվանդները հաճախ դիմում են, երբ ցավը ազդում է քայլելու, աստիճանների, աթոռից վեր կենալու կամ առօրյա գործողությունների վրա։",
    problem3Title: "Բուժումն այլեւս բավարար չէ",
    problem3Body: "Դեղերը, ֆիզիոթերապիան, ներարկումները, հանգիստը կամ քայլելու օժանդակ միջոցները կարող են որոշ ժամանակ օգնել։ Վիրահատությունը դիտարկվում է, երբ պահպանողական բուժումը այլեւս բավարար թեթեւացում չի տալիս։",
    problem4Title: "Նախկին պրոթեզի խնդիր",
    problem4Body: "Վերավիրահատություն կարող է պահանջվել թուլացման, մաշվածության, անկայունության, վարակի կամ նախկին հոդի փոխարինումից հետո շարունակվող ցավի դեպքում։",
    firstVisitEyebrow: "Ձեր առաջին այցը",
    firstVisitTitle: "Եկեք պատրաստված, որպեսզի խորհրդատվությունը հանգեցնի հստակ պլանի։",
    firstVisitBody: "Լավ առաջին այցը պետք է պարզի ախտորոշումը, վերանայի նախորդ բուժումը եւ որոշի՝ հաջորդ քայլը ոչ վիրահատական խնամքն է, լրացուցիչ քննությունները, թե վիրահատությունը։",
    bringTitle: "Բերեք ձեզ հետ",
    bring1: "Վերջին ռենտգենները, MRI, CT կամ նկարների CD-ները, եթե կան։",
    bring2: "Նախկին վիրահատությունների հաշվետվությունները, եթե արդեն ունեցել եք հոդի փոխարինում։",
    bring3: "Դեղերի ցուցակ, ալերգիաներ եւ բժշկական պատմություն։",
    bring4: "Ապահովագրության կամ երրորդ կողմ վճարողի տեղեկությունները։",
    expectTitle: "Ինչ սպասել այցի ընթացքում",
    expect1: "Քննարկում ցավի, ֆունկցիայի, քայլելու, աստիճանների եւ առօրյա սահմանափակումների մասին։",
    expect2: "Ուժի, շարժման, կայունության եւ քայլվածքի ֆիզիկական զննում։",
    expect3: "Նկարների վերանայում եւ հնարավոր նոր ռենտգենների կամ լաբորատոր քննությունների պահանջ։",
    expect4: "Բուժման տարբերակներ եւ հաջորդ քայլի գործնական պլան։",
    missingVisitTitle: "Դեռ պետք է լրացվի կլինիկայի կողմից",
    missingVisitBody: "Լրացնել: ավելացնել խորհրդատվության սպասվող տեւողությունը, ընդունվող ապահովագրությունները, խոսվող լեզուները՝ հայերեն/արաբերեն/ֆրանսերեն/անգլերեն, կայանման կամ իջեցման հրահանգները, եւ արդյոք հիվանդները պետք է ամրագրեն AUBMC-ի կամ գրասենյակի մենեջերի միջոցով։",
    careEyebrow: "Մասնագիտացված խնամք",
    careTitle: "Խնամքի ուղիներ կոնքի, ծնկի, վերավիրահատության եւ վարակված պրոթեզների դեպքերի համար։",
    care1Title: "Կոնքի ամբողջական փոխարինում",
    care1Body: "Կոնքի փոխարինումը հեռացնում է վնասված ոսկորն ու աճառը եւ հոդը փոխարինում պրոթեզային բաղադրիչներով։ Նպատակն է նվազեցնել ցավը, բարելավել շարժումը եւ հեշտացնել առօրյա ակտիվությունը։",
    care2Title: "Ծնկի ամբողջական փոխարինում",
    care2Body: "Ծնկի փոխարինումը փոխարինում է վնասված հոդային մակերեսները մետաղական եւ պլաստիկ բաղադրիչներով։ Այն դիտարկվում է, երբ ծանր արթրոզը կամ վնասվածքը սահմանափակում է ֆունկցիան, եւ այլ բուժումները այլեւս բավարար չեն։",
    care3Title: "Վերավիրահատություն եւ վարակված պրոթեզ",
    care3Body: "Դր. Կասիմը հատուկ հետաքրքրություն ունի կոնքի եւ ծնկի բարդ վերականգնման նկատմամբ, ներառյալ վարակված հոդային պրոթեզները։ Այս դեպքերը հաճախ պահանջում են մանրակրկիտ պլանավորում, փուլային բուժում եւ մոտ հետեւում։",
    journeyEyebrow: "Հիվանդի ուղին",
    journeyTitle: "Ինչ սպասել վիրահատությունից առաջ, հիվանդանոցում եւ տանը։",
    journeyBody: "Այս բաժինը միավորում է Դր. Կասիմի սկզբնական հրահանգները եւ հիվանդի համար հասկանալի ուղեցույցներ՝ հիմնված առաջատար օրթոպեդիկ հիվանդանոցների ռեսուրսների վրա։",
    step1Title: "Առաջին այց եւ որոշում",
    step1Body: "Վերանայվում են ձեր ախտանիշները, բժշկական պատմությունը, քայլելը, ուժը, շարժման ծավալը, ռենտգենները եւ նպատակները։ Խորհրդատվությունը պետք է պարզի՝ վիրահատությունը հիմա նպատակահարմար է, թե ոչ վիրահատական խնամքը պետք է շարունակվի։",
    step2Title: "Նախավիրահատական պատրաստություն",
    step2Body: "Քննությունները կարող են ներառել արյան քննություններ, մեզի քննություն, կրծքավանդակի ռենտգեն, ԷԿԳ եւ անզգայացման գնահատում։ Որոշ դեղեր կարող են պահանջվել դադարեցնել վիրահատությունից առաջ։ Լրացնել: ավելացնել ապահովագրության/նախնական հաստատման գործընթացը։",
    step3Title: "Պատրաստեք տունը",
    step3Body: "Պատրաստեք քայլակ կամ ձեռնափայտ, տուն վերադառնալու ուղեւորություն, օգնություն սննդի եւ լոգանքի համար, ապահով բռնակներ, հեռացրեք շարժվող գորգերը եւ քննարկեք բարձրացված զուգարանի նստատեղ կամ լոգանքի աթոռ, եթե խորհուրդ է տրվում։",
    step4Title: "Վիրահատություն եւ հիվանդանոցում մնալ",
    step4Body: "Կոնքի կամ ծնկի փոխարինումը սովորաբար տեւում է մոտ մեկից երկու ժամ՝ կախված բարդությունից։ Դր. Կասիմի սկզբնական հրահանգները նշում են, որ հիվանդանոցում մնալը սովորաբար երկուից չորս օր է։",
    step5Title: "Վաղ շարժում",
    step5Body: "Շնչառական վարժությունները, ցավի վերահսկումը, հակաբիոտիկները, հակամակարդիչները, վերքի խնամքը եւ ֆիզիոթերապիան սկսվում են վաղ։ Քայլելը սովորաբար սկսվում է քայլակի կամ հենակների օգնությամբ։",
    step6Title: "Վերականգնում տանը",
    step6Body: "Հետեւեք ֆիզիոթերապիայի պլանին, պաշտպանեք վերքը, փոխեք վիրակապերը ըստ ցուցումների եւ աստիճանաբար անցեք քայլակից ձեռնափայտի։ Վերականգնումը տարբեր է եւ կարող է պահանջել շաբաթներ կամ ամիսներ՝ ուժն ու վստահությունը վերականգնելու համար։",
    recoveryEyebrow: "Վերականգնման ժամանակացույց",
    recoveryTitle: "Վերականգնումը աստիճանական է։ Պլանը պետք է հստակ լինի տուն գնալուց առաջ։",
    recoveryBody: "Յուրաքանչյուր հիվանդ տարբեր է, բայց շատերին պետք է կառուցված պլան վերքի խնամքի, քայլելու աջակցության, ֆիզիոթերապիայի եւ հետեւման համար։",
    recovery1Label: "Հիվանդանոց",
    recovery1Title: "Առաջին օրերը",
    recovery1Body: "Ցավի վերահսկումը, շնչառական վարժությունները, հակամակարդիչները, վերքի հետեւումը եւ օգնությամբ քայլելը սկսվում են վաղ։",
    recovery2Label: "Տուն",
    recovery2Title: "Առաջին 2 շաբաթ",
    recovery2Body: "Կենտրոնացեք անվտանգ քայլելու, այտուցի վերահսկման, վերքը պաշտպանելու եւ ֆիզիոթերապիայի հրահանգներին հետեւելու վրա։",
    recovery3Label: "Հետեւում",
    recovery3Title: "Մոտ 3 շաբաթ",
    recovery3Body: "Դր. Կասիմի սկզբնական հրահանգներում նշվում է կարերի հեռացումը մոտ երեք շաբաթում՝ կախված վերքի ապաքինումից եւ վիճակից։",
    recovery4Label: "Ուժ",
    recovery4Title: "6-12 շաբաթ",
    recovery4Body: "Շատ հիվանդներ շարունակում են զարգացնել ուժը, հավասարակշռությունը, շարժման ծավալը եւ քայլելու վստահությունը։",
    recoveryPlaceholder: "Լրացնել: ավելացնել Դր. Կասիմի հստակ հետեւման ժամանակացույցը, ֆիզիոթերապիայի պրոտոկոլը, մեքենա վարելու ցուցումները, աշխատանքի վերադառնալու ցուցումները եւ ներբեռնվող վերքի խնամքի թերթիկը։",
    safetyEyebrow: "Անվտանգություն եւ վերականգնում",
    safetyTitle: "Հստակ հրահանգները կարեւոր են հոդի փոխարինումից հետո։",
    safety1Title: "Զանգահարեք կլինիկա, եթե կա",
    safety1Body: "Վերքի արտադրություն, աճող կարմրություն, անսովոր ցավ, ոտքի զգալի այտուց, շնչառության դժվարություն, ջերմություն կամ հանկարծակի ուժեղացող ցավ։",
    safety2Title: "Կոնքի նախազգուշացումներ",
    safety2Body: "Կախված վիրահատական մոտեցումից՝ հիվանդին կարող են ասել չխաչել ոտքերը, շատ չծալել կոնքը, չպտտվել կամ չնստել ցածր աթոռների վրա վաղ վերականգնման ընթացքում։",
    safety3Title: "Ակտիվության սպասումներ",
    safety3Body: "Վերականգնումից հետո սովորաբար նախընտրելի են ցածր ազդեցության ակտիվությունները։ Բարձր ազդեցության ակտիվությունը պետք է քննարկվի անմիջապես վիրաբույժի հետ։",
    aboutEyebrow: "Դր. Կասիմի մասին",
    aboutTitle: "Ֆելոուշիփով պատրաստված մեծահասակների վերականգնողական օրթոպեդ վիրաբույժ։",
    aboutBody1: "Դր. Կասիմը ավարտել է բակալավրիատը, բժշկական կրթությունը եւ օրթոպեդիայի ռեզիդենտուրան Ամերիկյան համալսարանում Բեյրութում։ Այնուհետեւ նա ավարտել է մեծահասակների վերականգնողական վիրաբուժության ֆելոուշիփը Մինեսոտայի համալսարանում ԱՄՆ-ում։",
    aboutBody2: "Նա հրապարակել է գրախոսված հոդվածներ, մասնակցել գրքերի գլուխների, զեկուցել տեղական եւ միջազգային մակարդակներում եւ մասնակցել կոնքի ու ծնկի արդյունքների նախագծերի։ Նրա հիմնական հետաքրքրությունը կոնքի եւ ծնկի բարդ վերականգնումն է՝ հատուկ շեշտադրումով վարակված հոդերի վրա։",
    staffTitle: "Գրասենյակի մենեջեր",
    staffName: "Ալիա Բարքի",
    staffPlaceholder: "Լրացնել: ավելացնել WhatsApp համար կամ նախընտրելի ժամադրության ընթացակարգ, եթե կիրառելի է։",
    faqEyebrow: "Հիվանդների հարցերը",
    faqTitle: "Գործնական պատասխաններ նախքան ժամադրությունը։",
    faq1Q: "Վիրահատությունից հետո ցավից լիովին ազատ կլինե՞մ։",
    faq1A: "Նպատակն է զգալիորեն նվազեցնել ցավը եւ բարելավել ֆունկցիան։ Վերականգնման ընթացքում որոշ անհարմարություն սպասելի է, եւ յուրաքանչյուր հիվանդ ապաքինվում է տարբեր կերպ։",
    faq2Q: "Երբ եմ քայլելու վիրահատությունից հետո։",
    faq2A: "Քայլելը սովորաբար սկսվում է վաղ՝ թիմի օգնությամբ եւ քայլակի կամ հենակների միջոցով։ Ֆիզիոթերապիան ուղղորդում է անվտանգ առաջընթացը։",
    faq3Q: "Որքա՞ն է հիվանդանոցում մնալը։",
    faq3A: "Դր. Կասիմի սկզբնական ուղեցույցը նշում է սովորական մնալը երկուից չորս օր՝ կախված վիրահատությունից եւ վերականգնումից։",
    faq4Q: "Ինձ պետք կլինի՞ վերականգնողական կենտրոն։",
    faq4A: "Սկզբնական FAQ-ում նշվում է, որ հիվանդների մեծ մասը տուն է վերադառնում պլանավորված ֆիզիոթերապիայի այցերով, բայց վերջնական պլանը կախված է անվտանգությունից, շարժունակությունից եւ բժշկական վիճակից։",
    faq5Q: "Ի՞նչ տեղեկություն է պակասում այս կայքում։",
    faq5A: "Լրացնել: ավելացնել ընդունվող ապահովագրությունները, կայանման/իջեցման հստակ հրահանգները, WhatsApp ամրագրման հասանելիությունը, խոսվող լեզուները, աշխատանքային ժամերից դուրս շտապ հրահանգները եւ ներբեռնվող նախավիրահատական ձեւերը։",
    originalFaqEyebrow: "Սկզբնական FAQ",
    originalFaqTitle: "Նախորդ կայքի մանրամասն հարցերը։",
    originalFaqBody: "Սրանք նախորդ կայքի հիվանդների հարցերն ու պատասխաններն են՝ վերակազմված ավելի մաքուր ձեւաչափով։",
    oldFaq1Q: "Հոդի փոխարինումը հիմա լավագույն բուժո՞ւմն է ինձ համար։",
    oldFaq1A: "Խնդրում ենք կարդալ հիվանդի կրթության բաժինը եւ խորհրդատվության ժամանակ քննարկել ոչ վիրահատական եւ վիրահատական տարբերակները։",
    oldFaq2Q: "Վիրահատությունը որքանո՞վ է արդյունավետ իմ տարիքում եւ բժշկական վիճակով։",
    oldFaq2A: "Վիրահատությունը կարող է լավ արդյունք տալ, բայց պլանը կախված է տարիքից, բժշկական խնդիրներից, ախտորոշումից եւ վիրահատության պատրաստվածությունից։",
    oldFaq3Q: "Կկարողանա՞մ քայլել առանց ցավի։",
    oldFaq3A: "Սկզբնական FAQ-ում նշվում է, որ հիվանդները պետք է կարողանան քայլել ազատորեն նվազագույն ցավով, բայց ոչ պարտադիր լիովին առանց ցավի։",
    oldFaq4Q: "Կկարողանա՞մ զբաղվել գոլֆով, լողով, թենիսով կամ արշավով։",
    oldFaq4A: "Սկզբնական FAQ-ում նշվում է, որ որոշ ակտիվություններ կարելի է քննարկել վիրահատությունից մոտ վեց ամիս հետո, սակայն արշավը խորհուրդ չի տրվում։",
    oldFaq5Q: "Ի՞նչ կարող եմ անել վիրահատությունից առաջ արդյունքը բարելավելու համար։",
    oldFaq5A: "Կարդացեք եւ հետեւեք հիվանդի կրթության հրահանգներին։ Վարժությունները, քայլակ կամ հենակներ օգտագործել սովորելը, ծխելը եւ ալկոհոլը դադարեցնելը եւ վիրահատության նախորդ գիշերը լոգանքը կարող են նվազեցնել ռիսկը։",
    oldFaq6Q: "Պե՞տք է նիհարեմ վիրահատությունից առաջ։",
    oldFaq6A: "Սկզբնական FAQ-ում նշվում է, որ քաշի կորուստը միշտ պարտադիր չէ, բայց կարող է օգնել։",
    oldFaq7Q: "Տուն վերադառնալիս որքան օգնության կարիք կունենամ։",
    oldFaq7A: "Սկզբնական FAQ-ում նշվում է, որ դուրս գրվելիս հիվանդները պետք է կարողանան ինքնուրույն գնալ զուգարան, բայց տան օգնությունը օգտակար է, հատկապես լոգանքի եւ անվտանգության համար։",
    oldFaq8Q: "Ինչպե՞ս տունը դարձնել ավելի անվտանգ։",
    oldFaq8A: "Խուսափեք սայթաքուն հատակներից եւ կոշիկներից։ Օգտագործեք խորհուրդ տրված միջոցները, օրինակ քայլակ, ձեռնափայտ եւ բարձրացված զուգարանի նստատեղ՝ կոնքի փոխարինումից հետո, եթե ցուցված է։",
    oldFaq9Q: "Պե՞տք է հիվանդանոցային մահճակալ կամ վերականգնողական կենտրոն։",
    oldFaq9A: "Սկզբնական FAQ-ում նշվում է, որ հիվանդանոցային մահճակալ սովորաբար պետք չէ, եթե բժիշկը չի պահանջում, եւ շատ հիվանդներ վերականգնողական կենտրոնի կարիք չունեն. ֆիզիոթերապիայի այցեր են նշանակվում։",
    oldFaq10Q: "Որո՞նք են ռիսկերը կամ բարդությունները։",
    oldFaq10A: "Նախորդ կայքում նշված ռիսկերն են վարակ, խորը երակային թրոմբոզ, նյարդաանոթային վնասում եւ անզգայացման հետ կապված ռիսկեր։",
    oldFaq11Q: "Արյան փոխներարկում պետք կլինի՞։",
    oldFaq11A: "Սկզբնական FAQ-ում նշվում է, որ ավտո-փոխներարկում չի օգտագործվում, եւ հիվանդները պետք է կապվեն արյան բանկի հետ, երբ դա պահանջվի։",
    oldFaq12Q: "Որքա՞ն կտեւեն վիրահատությունը եւ հիվանդանոցում մնալը։",
    oldFaq12A: "Սկզբնական FAQ-ում նշվում է, որ առաջնային վիրահատությունը մոտ մեկ ժամ եւ երեսուն րոպե է, վերավիրահատությունը մոտ երեք ժամ, իսկ հիվանդանոցում մնալը՝ երկուից չորս օր։",
    oldFaq13Q: "Ինչ տեսակի անզգայացում է օգտագործվելու։",
    oldFaq13A: "Անզգայացման տարբերակները քննարկվում են անեսթեզիոլոգի հետ։",
    oldFaq14Q: "Վիրահատությունից հետո ցավ կունենա՞մ։",
    oldFaq14A: "Վիրահատությունից հետո որոշ ցավ սպասելի է։ Ցավազրկող դեղերը վերականգնման մաս են։",
    oldFaq15Q: "Ե՞րբ կսկսեմ վեր կենալ եւ շարժվել։",
    oldFaq15A: "Սկզբնական FAQ-ում նշվում է, որ հիվանդները սովորաբար վեր են կենում եւ շարժվում վիրահատությունից հետո երկրորդ օրը՝ հիվանդանոցում ֆիզիոթերապիայի հետ։",
    oldFaq16Q: "Տուն կգնա՞մ քայլելով։",
    oldFaq16A: "Սկզբնական FAQ-ում նշվում է, որ հիվանդները տուն են գնում քայլելով, իսկ կոնքի վիրահատության հիվանդները դուրս են գրվում շտապօգնությամբ։",
    oldFaq17Q: "Պե՞տք է դադարեցնեմ դեղերը վիրահատությունից առաջ։",
    oldFaq17A: "Այո։ Հակամակարդիչները եւ որոշ այլ դեղեր կարող է պետք լինի դադարեցնել։ Գործը նշանակելիս պետք է խորհրդակցել բուժքույր-մենեջերի հետ։",
    bookingStepsEyebrow: "Ինչպես դառնալ հիվանդ",
    bookingStepsTitle: "Ժամադրության գործընթացը պետք է լինի պարզ եւ տեսանելի։",
    bookingStepsBody: "Օգտագործեք ստորեւ նշված գործող կլինիկայի համարները։ Պակասող գործնական մանրամասները ընդգծված են, որպեսզի լրացվեն կլինիկայի կողմից։",
    bookStep1Title: "Զանգահարել կամ գրել email",
    bookStep1Body: "Զանգահարեք AUBMC x 5860, զանգահարեք +961 (03) 526-229 կամ գրեք rk244@aub.edu.lb հասցեին։",
    bookStep2Title: "Հաստատել կլինիկայի օրը",
    bookStep2Body: "Սկզբնական կայքում նշված ժամերն են երկուշաբթի եւ չորեքշաբթի 8:00-16:30, ուրբաթ 13:00-17:00։",
    bookStep3Title: "Պատրաստել փաստաթղթերը",
    bookStep3Body: "Բերեք նկարներ, նախորդ հաշվետվություններ, դեղերի ցուցակ, բժշկական վիճակներ եւ ապահովագրական տեղեկություն։",
    bookStep4Title: "Պակասող ամրագրման ընթացակարգ",
    bookStep4Body: "Լրացնել: հաստատել՝ հիվանդները նախ պետք է զանգահարեն AUBMC, նախ զանգահարեն Ալիային, օգտագործեն WhatsApp, թե օգտագործեն հիվանդանոցի առցանց ժամադրության համակարգ։",
    contactEyebrow: "Ամրագրել ժամադրություն",
    contactTitle: "AUBMC կլինիկա՝ միայն ժամադրությամբ։",
    contactBody: "Կլինիկայի հասցե՝ Ամերիկյան համալսարանի բժշկական կենտրոն Բեյրութում, 4-րդ հարկ, Phase 1, արտաքին կլինիկայի մուտք։",
    contactCall: "Զանգահարել +961 (03) 526-229",
    contactEmail: "Գրել կլինիկային",
    scheduleTitle: "Կլինիկայի ժամեր",
    labelAubmc: "AUBMC:",
    labelMobile: "Բջջային:",
    labelEmail: "Email:",
    labelLinkedin: "LinkedIn:",
    labelFacebook: "Facebook:",
    locationsTitle: "Կլինիկայի վայրեր",
    loc1Title: "AUBMC",
    loc1Body: "4-րդ հարկ, Phase 1, արտաքին կլինիկայի մուտք",
    loc2Title: "Sahel General Hospital",
    loc2Body: "Ղոբեյրի, Բեյրութ, Լիբանան",
    loc3Title: "Clemenceau Medical Center",
    loc3Body: "Համրա, Բեյրութ, Լիբանան",
    loc4Title: "Rafik Hariri University Hospital",
    loc4Body: "Ջնահ, Բեյրութ, Լիբանան",
    loc5Title: "Bahman Hospital",
    loc5Body: "Հարեթ Հրեյք, Բեյրութ, Լիբանան",
    footerText: "Դր. Ռիդա Ադել Կասիմ | Կոնքի եւ ծնկի վերականգնողական վիրաբուժություն",
    backTop: "Վերադառնալ վերեւ"
  },
  ar: {
    topbarText: "عيادة المركز الطبي في الجامعة الأميركية في بيروت حسب الموعد",
    topbarAubmc: "+961 (01) 350-000 x 5860",
    topbarMobile: "+961 (03) 526-229",
    brandName: "د. رضا عادل قاسم",
    brandSub: "ترميم مفصل الورك والركبة",
    navWhen: "متى تراجع الطبيب",
    navSituations: "حالتك",
    navFirstVisit: "الزيارة الأولى",
    navCare: "العلاجات",
    navJourney: "رحلة الجراحة",
    navFaq: "الأسئلة",
    navAbout: "عن الطبيب",
    navBook: "احجز موعدا",
    heroEyebrow: "جراحة ترميم المفاصل للبالغين في بيروت",
    heroTitle: "رعاية متخصصة لاستبدال مفصل الورك والركبة عند الألم والتيبس والحالات المعقدة.",
    heroBody: "د. رضا عادل قاسم جراح عظم متخصص في استبدال مفصل الورك الكامل، واستبدال مفصل الركبة الكامل، وترميم الورك والركبة في الحالات المعقدة، وجراحة المراجعة، ورعاية التهاب المفصل الاصطناعي.",
    heroCta: "اتصل لحجز موعد",
    heroSecondary: "ماذا تتوقع",
    doctorName: "د. رضا عادل قاسم",
    doctorShort: "د. رضا قاسم",
    doctorSub: "طبيب، جراحة ترميم مفاصل البالغين",
    bookingEyebrow: "المواعيد",
    bookingTitle: "عيادة AUBMC الخارجية",
    bookingBody: "المركز الطبي في الجامعة الأميركية في بيروت، الطابق الرابع، المرحلة الأولى، مدخل العيادات الخارجية.",
    monday: "الاثنين",
    wednesday: "الأربعاء",
    friday: "الجمعة",
    hoursFull: "8:00 صباحا - 4:30 مساء",
    hoursFriday: "1:00 مساء - 5:00 مساء",
    proof1Label: "التدريب",
    proof1Title: "الجامعة الأميركية في بيروت + جامعة مينيسوتا",
    proof1Body: "دراسة الطب والإقامة في جراحة العظم في الجامعة الأميركية في بيروت، ثم زمالة في ترميم مفاصل البالغين في الولايات المتحدة.",
    proof2Label: "التركيز التخصصي",
    proof2Title: "حالات الورك والركبة المعقدة",
    proof2Body: "استبدال المفاصل، جراحة المراجعة، ورعاية التهاب المفصل الاصطناعي.",
    proof3Label: "العمل الأكاديمي",
    proof3Title: "أبحاث وفصول كتب",
    proof3Body: "أبحاث محكمة، تعليم، محاضرات، ومشاريع نتائج في جراحة مفاصل الورك والركبة.",
    situationsEyebrow: "اختر حالتك",
    situationsTitle: "اختر المسار الأقرب إلى مشكلتك.",
    situationsBody: "يصل المرضى عادة بإحدى أربع مشكلات رئيسية. اختر الحالة الأقرب، ثم احجز استشارة ومعك الصور والتقارير.",
    situation1Title: "لدي خشونة في الورك",
    situation1Body: "ألم الورك، التيبس، العرج، صعوبة لبس الحذاء أو الجوارب، وصعوبة المشي قد تعني أن مفصل الورك يحتاج إلى تقييم.",
    situation2Title: "لدي خشونة في الركبة",
    situation2Body: "ألم الركبة مع الدرج، النهوض من الكرسي، التورم، الاعوجاج، أو قصر مسافة المشي قد يحتاج إلى خطة علاج.",
    situation3Title: "لدي مفصل اصطناعي سابق",
    situation3Body: "الألم المستمر، عدم الثبات، الارتخاء، الاهتراء، أو تراجع الوظيفة بعد مفصل اصطناعي سابق قد يحتاج إلى تقييم جراحة مراجعة.",
    situation4Title: "قد يكون لدي التهاب في المفصل الاصطناعي",
    situation4Body: "الألم الجديد، إفرازات الجرح، الحرارة، التورم، أو تحاليل الدم غير الطبيعية بعد استبدال المفصل يجب أن تراجع بسرعة.",
    whenEyebrow: "متى تراجع الطبيب",
    whenTitle: "فكر باستشارة جراح عظم عندما يبدأ ألم المفصل بالتأثير على حياتك.",
    whenBody: "تشرح المراكز العظمية الكبرى استبدال مفصل الورك والركبة حول علامات واضحة: ألم مستمر، تيبس، ضعف في الحركة، صعوبة في المشي، صعوبة في صعود الدرج، وأعراض لم تعد تتحسن بشكل كاف مع العلاج غير الجراحي.",
    problem1Title: "خشونة الورك أو الركبة",
    problem1Body: "قد تؤدي خشونة المفصل إلى تآكل الغضروف تدريجيا، مما يسبب ألما وتيبسا ومحدودية في الحركة.",
    problem2Title: "المشي والدرج أصبحا أصعب",
    problem2Body: "كثير من المرضى يطلبون المساعدة عندما يؤثر الألم على المشي أو الدرج أو النهوض من الكرسي أو النشاطات اليومية.",
    problem3Title: "العلاج لم يعد كافيا",
    problem3Body: "قد تساعد الأدوية أو العلاج الفيزيائي أو الحقن أو الراحة أو العكاز لفترة. يتم التفكير بالجراحة عندما لا يعود العلاج المحافظ يعطي تحسنا مقبولا.",
    problem4Title: "مشكلة في مفصل اصطناعي سابق",
    problem4Body: "قد تكون جراحة المراجعة ضرورية عند الارتخاء أو الاهتراء أو عدم الثبات أو الالتهاب أو الألم المستمر بعد استبدال مفصل سابق.",
    firstVisitEyebrow: "زيارتك الأولى",
    firstVisitTitle: "احضر مستعدا حتى تؤدي الاستشارة إلى خطة واضحة.",
    firstVisitBody: "الزيارة الأولى الجيدة يجب أن توضح التشخيص، وتراجع العلاج السابق، وتحدد هل الخطوة التالية علاج غير جراحي أو فحوصات إضافية أو جراحة.",
    bringTitle: "أحضر معك",
    bring1: "صور أشعة حديثة أو MRI أو CT أو أقراص صور إذا كانت متوفرة.",
    bring2: "تقارير العمليات السابقة إذا كان لديك مفصل اصطناعي.",
    bring3: "قائمة الأدوية والحساسيات والتاريخ الطبي.",
    bring4: "معلومات التأمين أو الجهة الضامنة.",
    expectTitle: "ما المتوقع خلال الزيارة",
    expect1: "مناقشة الألم والوظيفة والمشي والدرج والقيود اليومية.",
    expect2: "فحص القوة والحركة والثبات وطريقة المشي.",
    expect3: "مراجعة الصور وربما طلب صور أو تحاليل حديثة.",
    expect4: "خيارات العلاج وخطة عملية للخطوة التالية.",
    missingVisitTitle: "معلومات ما زالت مطلوبة من العيادة",
    missingVisitBody: "عنصر مؤقت: أضف مدة الاستشارة المتوقعة، شركات التأمين المقبولة، اللغات المتاحة مثل العربية والفرنسية والإنجليزية، تعليمات المواقف والنزول، وهل يحجز المرضى عبر AUBMC أو عبر مديرة المكتب.",
    careEyebrow: "رعاية متخصصة",
    careTitle: "مسارات علاجية للورك والركبة وجراحة المراجعة والتهاب المفصل الاصطناعي.",
    care1Title: "استبدال مفصل الورك الكامل",
    care1Body: "تزيل جراحة استبدال الورك العظم والغضروف المتضررين وتستبدل المفصل بمكونات اصطناعية. الهدف هو تخفيف الألم وتحسين الحركة وتسهيل النشاط اليومي.",
    care2Title: "استبدال مفصل الركبة الكامل",
    care2Body: "تعيد جراحة استبدال الركبة تشكيل أسطح المفصل المتضررة باستخدام مكونات معدنية وبلاستيكية. يتم التفكير بها عندما تحد الخشونة الشديدة أو الإصابة من الوظيفة ولا تعود العلاجات الأخرى كافية.",
    care3Title: "جراحة المراجعة والتهاب المفصل الاصطناعي",
    care3Body: "يهتم د. قاسم بشكل خاص بترميم الورك والركبة في الحالات المعقدة، بما في ذلك التهاب المفاصل الاصطناعية. غالبا ما تحتاج هذه الحالات إلى تخطيط دقيق وعلاج مرحلي ومتابعة قريبة.",
    journeyEyebrow: "رحلة المريض",
    journeyTitle: "ماذا تتوقع قبل الجراحة، في المستشفى، وفي المنزل.",
    journeyBody: "يجمع هذا القسم بين تعليمات د. قاسم الأصلية وإرشادات مبسطة للمريض مستوحاة من موارد مستشفيات عظمية كبرى.",
    step1Title: "الزيارة الأولى واتخاذ القرار",
    step1Body: "تتم مراجعة الأعراض والتاريخ الطبي والمشي والقوة ومدى الحركة والصور الشعاعية والأهداف. يجب أن توضح الاستشارة ما إذا كانت الجراحة مناسبة الآن أو إذا كان يجب الاستمرار بالعلاج غير الجراحي.",
    step2Title: "التحضير قبل الجراحة",
    step2Body: "قد تشمل الفحوصات تحاليل دم، فحص بول، صورة صدر، تخطيط قلب، وتقييم التخدير. قد يطلب منك إيقاف بعض الأدوية قبل الجراحة. عنصر مؤقت: أضف مسار التأمين والموافقة المسبقة.",
    step3Title: "تحضير المنزل",
    step3Body: "جهز مشاية أو عكازا، ورتب وسيلة نقل إلى المنزل، ومساعدة في الطعام والاستحمام، وثبت الدرابزين، وأزل السجاد غير الثابت، وفكر بكرسي مرحاض مرتفع أو كرسي للاستحمام إذا أوصى الطبيب.",
    step4Title: "الجراحة والإقامة في المستشفى",
    step4Body: "تستغرق جراحة استبدال الورك أو الركبة عادة حوالي ساعة إلى ساعتين بحسب صعوبة الحالة. تشير تعليمات د. قاسم الأصلية إلى أن الإقامة غالبا بين يومين وأربعة أيام.",
    step5Title: "الحركة المبكرة",
    step5Body: "تبدأ تمارين التنفس وضبط الألم والمضادات الحيوية ومضادات التخثر والعناية بالجرح والعلاج الفيزيائي مبكرا. يبدأ المشي عادة بدعم من مشاية أو عكازين.",
    step6Title: "التعافي في المنزل",
    step6Body: "اتبع خطة العلاج الفيزيائي، وحافظ على الجرح محميا، وغير الضمادات كما هو مطلوب، وتقدم تدريجيا من المشاية إلى العكاز. يختلف التعافي بين المرضى وقد يحتاج إلى أسابيع أو أشهر لاستعادة القوة والثقة.",
    recoveryEyebrow: "جدول التعافي",
    recoveryTitle: "التعافي تدريجي. يجب أن تكون الخطة واضحة قبل مغادرة المستشفى.",
    recoveryBody: "كل مريض يختلف عن الآخر، لكن معظم المرضى يحتاجون إلى خطة واضحة للعناية بالجرح، والمشي، والعلاج الفيزيائي، والمتابعة.",
    recovery1Label: "المستشفى",
    recovery1Title: "الأيام الأولى",
    recovery1Body: "يبدأ ضبط الألم وتمارين التنفس ومضادات التخثر ومراقبة الجرح والمشي بمساعدة الفريق مبكرا.",
    recovery2Label: "المنزل",
    recovery2Title: "أول أسبوعين",
    recovery2Body: "التركيز يكون على المشي الآمن، تخفيف التورم، حماية الجرح، واتباع تعليمات العلاج الفيزيائي.",
    recovery3Label: "المتابعة",
    recovery3Title: "حوالي 3 أسابيع",
    recovery3Body: "تشير تعليمات د. قاسم الأصلية إلى إزالة الغرز بعد حوالي ثلاثة أسابيع، بحسب التئام الجرح وحالته.",
    recovery4Label: "القوة",
    recovery4Title: "6-12 أسبوعا",
    recovery4Body: "يواصل كثير من المرضى بناء القوة والتوازن ومدى الحركة والثقة بالمشي.",
    recoveryPlaceholder: "عنصر مؤقت: أضف جدول المتابعة الدقيق لد. قاسم، بروتوكول العلاج الفيزيائي، إرشادات القيادة، العودة إلى العمل، ونشرة عناية بالجرح قابلة للتحميل.",
    safetyEyebrow: "السلامة والتعافي",
    safetyTitle: "التعليمات الواضحة مهمة بعد استبدال المفصل.",
    safety1Title: "اتصل بالعيادة عند",
    safety1Body: "وجود إفرازات من الجرح، ازدياد الاحمرار، ألم غير معتاد، تورم واضح في الساق، صعوبة في التنفس، حرارة، أو ألم مفاجئ يزداد بسرعة.",
    safety2Title: "احتياطات الورك",
    safety2Body: "بحسب طريقة الجراحة، قد يطلب من المريض عدم تقاطع الساقين، وعدم ثني الورك كثيرا، وعدم الالتفاف، وعدم الجلوس على كراسي منخفضة في فترة التعافي الأولى.",
    safety3Title: "توقعات النشاط",
    safety3Body: "يفضل عادة النشاط منخفض التأثير بعد التعافي. يجب مناقشة النشاط العالي التأثير مباشرة مع الجراح.",
    aboutEyebrow: "عن د. قاسم",
    aboutTitle: "جراح عظم متخصص بزمالة في ترميم مفاصل البالغين.",
    aboutBody1: "أكمل د. قاسم دراسته الجامعية، ودراسة الطب، والإقامة في جراحة العظم في الجامعة الأميركية في بيروت. ثم أكمل زمالة في جراحة ترميم مفاصل البالغين في جامعة مينيسوتا في الولايات المتحدة.",
    aboutBody2: "نشر أبحاثا محكمة، وساهم في فصول كتب، وقدم محاضرات محليا ودوليا، وشارك في مشاريع نتائج للورك والركبة. اهتمامه الأساسي هو ترميم الورك والركبة في الحالات المعقدة مع تركيز خاص على التهاب المفاصل الاصطناعية.",
    staffTitle: "مديرة المكتب",
    staffName: "عليا بركي",
    staffPlaceholder: "عنصر مؤقت: أضف رقم واتساب أو طريقة الحجز المفضلة إذا كانت متوفرة.",
    faqEyebrow: "أسئلة يطرحها المرضى",
    faqTitle: "إجابات عملية قبل الحجز.",
    faq1Q: "هل سأكون بلا ألم بعد الجراحة؟",
    faq1A: "الهدف هو تخفيف الألم بشكل واضح وتحسين الوظيفة. بعض الانزعاج متوقع خلال التعافي، وكل مريض يلتئم بطريقة مختلفة.",
    faq2Q: "متى أمشي بعد الجراحة؟",
    faq2A: "يبدأ المشي عادة مبكرا بمساعدة الفريق الطبي وباستخدام مشاية أو عكازين. يوجه العلاج الفيزيائي التقدم بشكل آمن.",
    faq3Q: "كم تستغرق الإقامة في المستشفى؟",
    faq3A: "تشير تعليمات د. قاسم الأصلية إلى إقامة نموذجية بين يومين وأربعة أيام، بحسب نوع الجراحة والتعافي.",
    faq4Q: "هل أحتاج إلى مركز تأهيل؟",
    faq4A: "تذكر الأسئلة الشائعة الأصلية أن معظم المرضى يعودون إلى المنزل مع زيارات علاج فيزيائي مجدولة، لكن الخطة النهائية تعتمد على السلامة والحركة والحالة الطبية.",
    faq5Q: "ما المعلومات الناقصة في هذا الموقع؟",
    faq5A: "عنصر مؤقت: أضف شركات التأمين المقبولة، تعليمات المواقف والنزول، توفر الحجز عبر واتساب، اللغات، تعليمات الطوارئ خارج الدوام، ونماذج ما قبل الجراحة القابلة للتحميل.",
    originalFaqEyebrow: "الأسئلة الأصلية",
    originalFaqTitle: "أسئلة مفصلة من الموقع السابق.",
    originalFaqBody: "هذه أسئلة وأجوبة المرضى من الموقع السابق، أعيد تنظيمها بصيغة أوضح.",
    oldFaq1Q: "هل استبدال المفصل هو أفضل علاج لي الآن؟",
    oldFaq1A: "يرجى مراجعة قسم تثقيف المرضى ومناقشة الخيارات غير الجراحية والجراحية خلال الاستشارة.",
    oldFaq2Q: "ما مدى نجاح الجراحة لشخص في عمري ومع مشاكلي الطبية؟",
    oldFaq2A: "قد تنجح الجراحة بشكل جيد، لكن الخطة تعتمد على العمر والمشاكل الطبية والتشخيص والاستعداد للجراحة.",
    oldFaq3Q: "هل سأتمكن من المشي من دون ألم؟",
    oldFaq3A: "تذكر الأسئلة الأصلية أن المريض يجب أن يتمكن من المشي بحرية مع ألم قليل، لكن ليس بالضرورة من دون أي ألم.",
    oldFaq4Q: "هل سأتمكن من ممارسة نشاطات مثل الغولف أو السباحة أو التنس أو المشي الجبلي؟",
    oldFaq4A: "تذكر الأسئلة الأصلية أن بعض النشاطات يمكن التفكير بها بعد حوالي ستة أشهر من الجراحة، لكن المشي الجبلي غير منصوح به.",
    oldFaq5Q: "ماذا يمكنني أن أفعل قبل الجراحة لتحسين النتيجة؟",
    oldFaq5A: "اقرأ تعليمات تثقيف المرضى واتبعها. التمارين، تعلم استخدام المشاية أو العكاز، إيقاف التدخين والكحول، والاستحمام ليلة الجراحة قد تساعد على تقليل المخاطر.",
    oldFaq6Q: "هل أحتاج إلى إنقاص الوزن قبل الجراحة؟",
    oldFaq6A: "تذكر الأسئلة الأصلية أن إنقاص الوزن ليس ضروريا دائما، لكنه يساعد.",
    oldFaq7Q: "كم سأحتاج من المساعدة عند العودة إلى المنزل؟",
    oldFaq7A: "تذكر الأسئلة الأصلية أن المريض يجب أن يستطيع الذهاب إلى الحمام وحده عند الخروج، لكن المساعدة في المنزل تبقى مفيدة، خاصة للاستحمام والسلامة.",
    oldFaq8Q: "كيف أجعل منزلي أكثر أمانا؟",
    oldFaq8A: "تجنب الأرضيات أو الأحذية الزلقة. استخدم الوسائل الموصى بها مثل المشاية والعكاز ورافعة مقعد المرحاض بعد استبدال الورك إذا طلب ذلك.",
    oldFaq9Q: "هل أحتاج إلى سرير مستشفى أو مركز تأهيل؟",
    oldFaq9A: "تذكر الأسئلة الأصلية أن سرير المستشفى لا يلزم عادة إلا إذا طلب الطبيب، وأن معظم المرضى لا يحتاجون إلى مركز تأهيل؛ تتم جدولة زيارات علاج فيزيائي.",
    oldFaq10Q: "ما هي المخاطر أو المضاعفات؟",
    oldFaq10A: "تشمل المخاطر المذكورة في الموقع السابق الالتهاب، الخثار الوريدي العميق، إصابة الأعصاب أو الأوعية، ومخاطر التخدير.",
    oldFaq11Q: "هل سأحتاج إلى نقل دم؟",
    oldFaq11A: "تذكر الأسئلة الأصلية أن النقل الذاتي للدم لا يستخدم، وأن على المريض الاتصال ببنك الدم لترتيب الدم عند الطلب.",
    oldFaq12Q: "كم تستغرق الجراحة والإقامة في المستشفى؟",
    oldFaq12A: "تصف الأسئلة الأصلية الجراحة الأولية بحوالي ساعة وثلاثين دقيقة، وجراحة المراجعة بحوالي ثلاث ساعات، والإقامة في المستشفى بين يومين وأربعة أيام.",
    oldFaq13Q: "ما نوع التخدير المستخدم؟",
    oldFaq13A: "تتم مناقشة خيارات التخدير مع طبيب التخدير.",
    oldFaq14Q: "هل سيكون لدي ألم بعد الجراحة؟",
    oldFaq14A: "بعض الألم متوقع بعد الجراحة. يتم تقديم أدوية الألم كجزء من التعافي.",
    oldFaq15Q: "متى سأبدأ بالنهوض والحركة؟",
    oldFaq15A: "تذكر الأسئلة الأصلية أن المرضى يبدأون عادة بالنهوض والحركة في اليوم الثاني بعد الجراحة مع العلاج الفيزيائي في المستشفى.",
    oldFaq16Q: "هل سأخرج إلى المنزل وأنا أمشي؟",
    oldFaq16A: "تذكر الأسئلة الأصلية أن المرضى يخرجون إلى المنزل وهم قادرون على المشي، وأن مرضى جراحة الورك يخرجون إلى المنزل بسيارة إسعاف.",
    oldFaq17Q: "هل أحتاج إلى إيقاف أدوية قبل الجراحة؟",
    oldFaq17A: "نعم. قد تحتاج مضادات التخثر وبعض الأدوية الأخرى إلى الإيقاف. يجب استشارة مسؤولة التمريض عند جدولة الحالة.",
    bookingStepsEyebrow: "كيف تصبح مريضا في العيادة",
    bookingStepsTitle: "يجب أن تكون طريقة الحجز بسيطة وواضحة.",
    bookingStepsBody: "استخدم أرقام العيادة الحالية أدناه. تم تمييز التفاصيل التشغيلية الناقصة حتى تستكملها العيادة.",
    bookStep1Title: "اتصل أو أرسل بريدا",
    bookStep1Body: "اتصل بـ AUBMC x 5860، أو +961 (03) 526-229، أو أرسل بريدا إلى rk244@aub.edu.lb.",
    bookStep2Title: "أكد يوم العيادة",
    bookStep2Body: "الأوقات المذكورة في الموقع الأصلي هي الاثنين والأربعاء من 8:00 صباحا حتى 4:30 مساء، والجمعة من 1:00 حتى 5:00 مساء.",
    bookStep3Title: "جهز ملفاتك",
    bookStep3Body: "أحضر الصور، والتقارير السابقة، وقائمة الأدوية، والحالات الطبية، ومعلومات التأمين.",
    bookStep4Title: "طريقة الحجز الناقصة",
    bookStep4Body: "عنصر مؤقت: أكد هل يجب على المرضى الاتصال بـ AUBMC أولا، أو الاتصال بعليا أولا، أو استخدام واتساب، أو استخدام نظام مواعيد إلكتروني للمستشفى.",
    contactEyebrow: "احجز موعدا",
    contactTitle: "عيادة AUBMC حسب الموعد.",
    contactBody: "مكان العيادة: المركز الطبي في الجامعة الأميركية في بيروت، الطابق الرابع، المرحلة الأولى، مدخل العيادات الخارجية.",
    contactCall: "اتصل +961 (03) 526-229",
    contactEmail: "راسل العيادة",
    scheduleTitle: "أوقات العيادة",
    labelAubmc: "AUBMC:",
    labelMobile: "الجوال:",
    labelEmail: "البريد:",
    labelLinkedin: "لينكدإن:",
    labelFacebook: "فيسبوك:",
    locationsTitle: "مواقع العيادة",
    loc1Title: "AUBMC",
    loc1Body: "الطابق الرابع، المرحلة الأولى، مدخل العيادات الخارجية",
    loc2Title: "مستشفى الساحل العام",
    loc2Body: "الغبيري، بيروت، لبنان",
    loc3Title: "مركز كليمنصو الطبي",
    loc3Body: "الحمرا، بيروت، لبنان",
    loc4Title: "مستشفى رفيق الحريري الجامعي",
    loc4Body: "الجناح، بيروت، لبنان",
    loc5Title: "مستشفى بهمن",
    loc5Body: "حارة حريك، بيروت، لبنان",
    footerText: "د. رضا عادل قاسم | جراحة ترميم مفاصل الورك والركبة للبالغين",
    backTop: "العودة للأعلى"
  }
};

const sourceFaqs = {
  en: [
    ["Is joint replacement the best treatment for me right now? What other treatments should I think about?", "Please refer to the Surgery Journey section."],
    ["How well does this surgery work for someone my age and with any of the medical problems I may have?", "Surgery works well. Please refer to the Surgery Journey section for more information."],
    ["Will I be able to walk without pain? How far?", "You will be able to walk freely with minimum pain, not pain free."],
    ["Will I be able to do other activities, such as golf, swimming, tennis, or hiking? When can I do them?", "Six months post-surgery, although hiking is not advisable."],
    ["Is there anything that I can do before the surgery so it will be more successful for me?", "Read our instructions in the Surgery Journey section and follow them."],
    ["Are there exercises I should do to make my muscles stronger?", "Yes, you will be taught to do them prior to the surgery."],
    ["Can I learn to use crutches or a walker before I have the surgery?", "Yes, it is advisable."],
    ["Do I need to lose weight before surgery?", "No need, but if you do it it helps."],
    ["How much help will I need when I come home? Will I be able to get out of bed?", "Yes, upon discharge you will be able to go to the bathroom by yourself."],
    ["How can I make my home safer for me?", "Avoid slippery grounds or shoes."],
    ["How can I make it easier for myself in the bathroom and shower?", "You need help in shower to protect your wound by isolating it from water then sit on a chair."],
    ["What type of supplies will I need when I get home?", "Walker, cane, toilet seat raise for patient who undergo total hip."],
    ["Do I need to rearrange my home?", "No."],
    ["What should I do if there are steps that go to my bedroom or bathroom?", "Need assistance, but still few steps are allowed."],
    ["Do I need a hospital bed?", "No, unless requested by your physician."],
    ["Do I need to go to a rehabilitation facility?", "No, a physiotherapist will be on a scheduled visit."],
    ["What are the risks or complications of the surgery?", "Please refer to the Surgery Journey section."],
    ["What can I do before surgery to make the risks lower?", "Stop alcohol and smoking, do bath night of surgery and exercises."],
    ["For which of my medical problems (diabetes, heart disease, high blood pressure) do I need to see my doctor?", "For all."],
    ["Will I need a blood transfusion during or after the surgery? Isn't there a way of saving my blood before the surgery so it can be used during the surgery?", "We are not doing auto-transfusion. You need to contact blood bank to arrange for blood whenever you are asked for."],
    ["How long will the surgery last?", "Surgery is around one hour and 30 minutes for primary surgery and around three hours for revision. As for hospital stay, it ranges between two to four days."],
    ["What type of anesthesia will be used? Are there choices to consider?", "Discussed with the anesthesiologist."],
    ["Will I be in a lot of pain after surgery?", "Will have pain."],
    ["What will be done to relieve the pain?", "Yes, of course."],
    ["How soon will I be getting up and moving around?", "The second day after the surgery."],
    ["How do I get to the bathroom after surgery? Would I have a catheter in my bladder?", "No unless you did not void in 8 hours post surgery."],
    ["Will I have physical therapy in the hospital?", "Yes, one session postoperatively."],
    ["What other types of treatment or therapy will I have at the hospital?", "IV antibiotics and analgesia."],
    ["How long do I need to be in the hospital?", "Between two to four days."],
    ["Will I be able to walk when I leave the hospital? Will I be able to go home after being in the hospital, or will I need to go somewhere else to recover more?", "You will go home ambulatory second day of surgery. Total hip surgery patients will be discharged home with an ambulance."],
    ["Do I need to stop taking any medicines before my surgery?", "Yes, anticoagulation and some other drugs. Consult the nurse manager upon scheduling your case."]
  ],
  fr: [
    ["Le remplacement articulaire est-il le meilleur traitement pour moi maintenant ? Quels autres traitements dois-je envisager ?", "Veuillez consulter la section d'education du patient."],
    ["Quelle est l'efficacite de cette chirurgie pour une personne de mon age et avec mes problemes medicaux ?", "La chirurgie fonctionne bien. Veuillez consulter la section d'education du patient pour plus d'informations."],
    ["Pourrai-je marcher sans douleur ? Quelle distance ?", "Vous pourrez marcher librement avec une douleur minimale, mais pas totalement sans douleur."],
    ["Pourrai-je faire des activites comme le golf, la natation, le tennis ou la randonnee ? Quand ?", "Six mois apres la chirurgie, bien que la randonnee ne soit pas conseillee."],
    ["Y a-t-il quelque chose que je puisse faire avant la chirurgie pour ameliorer le resultat ?", "Lisez les consignes dans la section d'education du patient et suivez-les."],
    ["Y a-t-il des exercices pour renforcer mes muscles ?", "Oui, ils vous seront enseignes avant la chirurgie."],
    ["Puis-je apprendre a utiliser des bequilles ou une marchette avant la chirurgie ?", "Oui, c'est conseille."],
    ["Dois-je perdre du poids avant la chirurgie ?", "Ce n'est pas obligatoire, mais cela aide."],
    ["De quelle aide aurai-je besoin a la maison ? Pourrai-je sortir du lit ?", "Oui, a la sortie vous devriez pouvoir aller aux toilettes par vous-meme."],
    ["Comment rendre ma maison plus sure ?", "Evitez les sols ou chaussures glissants."],
    ["Comment faciliter la salle de bain et la douche ?", "Vous aurez besoin d'aide pour la douche afin de proteger la plaie de l'eau, puis vous asseoir sur une chaise."],
    ["De quelles fournitures aurai-je besoin a la maison ?", "Marchette, canne et siege de toilette sureleve pour les patients ayant une prothese totale de hanche."],
    ["Dois-je rearranger ma maison ?", "Non."],
    ["Que faire s'il y a des marches vers ma chambre ou ma salle de bain ?", "Une aide est necessaire, mais quelques marches restent permises."],
    ["Ai-je besoin d'un lit d'hopital ?", "Non, sauf si votre medecin le demande."],
    ["Dois-je aller dans un centre de rehabilitation ?", "Non, un physiotherapeute aura des visites programmees."],
    ["Quels sont les risques ou complications de la chirurgie ?", "Veuillez consulter la section d'education du patient."],
    ["Que puis-je faire avant la chirurgie pour reduire les risques ?", "Arreter alcool et tabac, prendre un bain la veille de la chirurgie et faire les exercices."],
    ["Pour quels problemes medicaux dois-je voir mon medecin ?", "Pour tous."],
    ["Aurai-je besoin d'une transfusion pendant ou apres la chirurgie ? Peut-on conserver mon sang avant la chirurgie ?", "Nous ne faisons pas d'auto-transfusion. Vous devez contacter la banque du sang pour organiser le sang lorsqu'on vous le demande."],
    ["Combien de temps durera la chirurgie ?", "Environ 1 h 30 pour une chirurgie primaire et environ 3 heures pour une revision. Le sejour hospitalier varie entre deux et quatre jours."],
    ["Quel type d'anesthesie sera utilise ? Y a-t-il des choix ?", "A discuter avec l'anesthesiologiste."],
    ["Aurai-je beaucoup de douleur apres la chirurgie ?", "Il y aura de la douleur."],
    ["Que fera-t-on pour soulager la douleur ?", "Oui, bien sur."],
    ["Quand vais-je me lever et bouger ?", "Le deuxieme jour apres la chirurgie."],
    ["Comment irai-je aux toilettes apres la chirurgie ? Aurai-je une sonde urinaire ?", "Non, sauf si vous n'avez pas urine 8 heures apres la chirurgie."],
    ["Aurai-je de la physiotherapie a l'hopital ?", "Oui, une seance apres l'operation."],
    ["Quels autres traitements aurai-je a l'hopital ?", "Antibiotiques IV et analgesie."],
    ["Combien de temps dois-je rester a l'hopital ?", "Entre deux et quatre jours."],
    ["Pourrai-je marcher en quittant l'hopital ? Irai-je a la maison ou ailleurs ?", "Vous rentrerez a domicile en marchant le deuxieme jour. Les patients de chirurgie de hanche totale sortiront en ambulance."],
    ["Dois-je arreter certains medicaments avant la chirurgie ?", "Oui, anticoagulation et certains autres medicaments. Consultez la nurse manager lors de la programmation."]
  ],
  ar: [
    ["هل استبدال المفصل هو العلاج الأفضل لي الآن؟ وما العلاجات الأخرى التي يجب التفكير بها؟", "يرجى مراجعة قسم تثقيف المرضى."],
    ["ما مدى نجاح هذه الجراحة لشخص في عمري ومع أي مشاكل طبية لدي؟", "الجراحة تعمل بشكل جيد. يرجى مراجعة قسم تثقيف المرضى لمزيد من المعلومات."],
    ["هل سأتمكن من المشي من دون ألم؟ وكم المسافة؟", "ستتمكن من المشي بحرية مع ألم بسيط، وليس من دون ألم تماما."],
    ["هل سأتمكن من ممارسة نشاطات مثل الغولف أو السباحة أو التنس أو المشي الجبلي؟ ومتى؟", "بعد ستة أشهر من الجراحة، مع أن المشي الجبلي غير منصوح به."],
    ["هل هناك شيء يمكنني فعله قبل الجراحة لتكون أكثر نجاحا؟", "اقرأ تعليمات قسم تثقيف المرضى واتبعها."],
    ["هل هناك تمارين يجب أن أقوم بها لتقوية العضلات؟", "نعم، سيتم تعليمك إياها قبل الجراحة."],
    ["هل يمكنني تعلم استخدام العكازات أو المشاية قبل الجراحة؟", "نعم، هذا مستحسن."],
    ["هل أحتاج إلى إنقاص الوزن قبل الجراحة؟", "ليس ضروريا، لكنه يساعد إذا فعلت ذلك."],
    ["كم سأحتاج من المساعدة عند العودة إلى المنزل؟ وهل سأتمكن من النهوض من السرير؟", "نعم، عند الخروج ستتمكن من الذهاب إلى الحمام بنفسك."],
    ["كيف أجعل منزلي أكثر أمانا؟", "تجنب الأرضيات أو الأحذية الزلقة."],
    ["كيف أجعل الحمام والاستحمام أسهل؟", "تحتاج إلى مساعدة في الاستحمام لحماية الجرح بعزله عن الماء ثم الجلوس على كرسي."],
    ["ما الأدوات التي أحتاجها عند العودة إلى المنزل؟", "مشاية، عكاز، ورافعة مقعد المرحاض لمن خضع لاستبدال الورك الكامل."],
    ["هل أحتاج إلى إعادة ترتيب منزلي؟", "لا."],
    ["ماذا أفعل إذا كانت هناك درجات إلى غرفة النوم أو الحمام؟", "تحتاج إلى مساعدة، لكن بضع درجات مسموحة."],
    ["هل أحتاج إلى سرير مستشفى؟", "لا، إلا إذا طلب الطبيب ذلك."],
    ["هل أحتاج إلى الذهاب إلى مركز تأهيل؟", "لا، سيكون هناك معالج فيزيائي بزيارات مجدولة."],
    ["ما هي مخاطر أو مضاعفات الجراحة؟", "يرجى مراجعة قسم تثقيف المرضى."],
    ["ماذا يمكنني أن أفعل قبل الجراحة لتقليل المخاطر؟", "أوقف الكحول والتدخين، واستحم ليلة الجراحة، وقم بالتمارين."],
    ["لأي من مشاكلي الطبية يجب أن أراجع طبيبي؟", "لكلها."],
    ["هل سأحتاج إلى نقل دم أثناء أو بعد الجراحة؟ أليس هناك طريقة لحفظ دمي قبل الجراحة؟", "لا نقوم بالنقل الذاتي للدم. يجب الاتصال ببنك الدم لترتيب الدم عندما يطلب منك ذلك."],
    ["كم ستستغرق الجراحة؟", "حوالي ساعة وثلاثين دقيقة للجراحة الأولية وحوالي ثلاث ساعات لجراحة المراجعة. أما الإقامة في المستشفى فهي بين يومين وأربعة أيام."],
    ["ما نوع التخدير المستخدم؟ وهل هناك خيارات؟", "يتم مناقشته مع طبيب التخدير."],
    ["هل سأشعر بألم كثير بعد الجراحة؟", "سيكون هناك ألم."],
    ["ماذا سيتم فعله لتخفيف الألم؟", "نعم، بالطبع."],
    ["متى سأبدأ بالنهوض والحركة؟", "في اليوم الثاني بعد الجراحة."],
    ["كيف أذهب إلى الحمام بعد الجراحة؟ وهل سيكون لدي قسطرة بولية؟", "لا، إلا إذا لم تتبول خلال 8 ساعات بعد الجراحة."],
    ["هل سأحصل على علاج فيزيائي في المستشفى؟", "نعم، جلسة واحدة بعد الجراحة."],
    ["ما العلاجات الأخرى التي سأحصل عليها في المستشفى؟", "مضادات حيوية وريدية ومسكنات."],
    ["كم أحتاج أن أبقى في المستشفى؟", "بين يومين وأربعة أيام."],
    ["هل سأتمكن من المشي عند مغادرة المستشفى؟ وهل سأذهب إلى المنزل أم إلى مكان آخر؟", "ستذهب إلى المنزل ماشيا في اليوم الثاني من الجراحة. مرضى جراحة الورك الكاملة يخرجون إلى المنزل بسيارة إسعاف."],
    ["هل أحتاج إلى إيقاف أي أدوية قبل الجراحة؟", "نعم، مضادات التخثر وبعض الأدوية الأخرى. راجع مسؤولة التمريض عند جدولة الحالة."]
  ],
  hy: [
    ["Հոդի փոխարինումը հիմա լավագույն բուժո՞ւմն է ինձ համար։ Ի՞նչ այլ բուժումներ պետք է մտածեմ։", "Խնդրում ենք կարդալ հիվանդի կրթության բաժինը։"],
    ["Այս վիրահատությունը որքանո՞վ է արդյունավետ իմ տարիքում եւ իմ բժշկական խնդիրներով։", "Վիրահատությունը լավ է աշխատում։ Լրացուցիչ տեղեկության համար կարդացեք հիվանդի կրթության բաժինը։"],
    ["Կկարողանա՞մ քայլել առանց ցավի։ Որքա՞ն հեռու։", "Կկարողանաք քայլել ազատորեն նվազագույն ցավով, բայց ոչ լիովին առանց ցավի։"],
    ["Կկարողանա՞մ անել գոլֆ, լող, թենիս կամ արշավ։ Ե՞րբ։", "Վիրահատությունից վեց ամիս հետո, սակայն արշավը խորհուրդ չի տրվում։"],
    ["Կա՞ ինչ-որ բան, որ կարող եմ անել վիրահատությունից առաջ՝ հաջողությունն ավելացնելու համար։", "Կարդացեք հիվանդի կրթության բաժնի հրահանգները եւ հետեւեք դրանց։"],
    ["Կա՞ն վարժություններ մկաններս ուժեղացնելու համար։", "Այո, դրանք ձեզ կսովորեցնեն վիրահատությունից առաջ։"],
    ["Կարո՞ղ եմ սովորել օգտագործել հենակներ կամ քայլակ վիրահատությունից առաջ։", "Այո, խորհուրդ է տրվում։"],
    ["Պե՞տք է նիհարեմ վիրահատությունից առաջ։", "Պարտադիր չէ, բայց եթե նիհարեք, դա կօգնի։"],
    ["Տուն վերադառնալիս որքան օգնության կարիք կունենամ։ Կկարողանա՞մ վեր կենալ անկողնուց։", "Այո, դուրս գրվելիս կկարողանաք ինքնուրույն գնալ զուգարան։"],
    ["Ինչպե՞ս տունը դարձնել ավելի անվտանգ։", "Խուսափեք սայթաքուն հատակներից կամ կոշիկներից։"],
    ["Ինչպե՞ս հեշտացնել լոգարանը եւ ցնցուղը։", "Ցնցուղի ժամանակ օգնություն է պետք՝ վերքը ջրից պաշտպանելու համար, ապա նստեք աթոռի վրա։"],
    ["Ինչ պարագաներ պետք կլինեն տանը։", "Քայլակ, ձեռնափայտ եւ բարձրացված զուգարանի նստատեղ կոնքի ամբողջական փոխարինում անցած հիվանդի համար։"],
    ["Պե՞տք է վերադասավորեմ տունը։", "Ոչ։"],
    ["Ի՞նչ անել, եթե աստիճաններ կան դեպի ննջասենյակ կամ լոգարան։", "Օգնություն է պետք, բայց մի քանի աստիճան թույլատրելի է։"],
    ["Պե՞տք է հիվանդանոցային մահճակալ։", "Ոչ, եթե բժիշկը չի պահանջում։"],
    ["Պե՞տք է գնամ վերականգնողական կենտրոն։", "Ոչ, ֆիզիոթերապեւտը կունենա պլանավորված այցեր։"],
    ["Որո՞նք են վիրահատության ռիսկերը կամ բարդությունները։", "Խնդրում ենք կարդալ հիվանդի կրթության բաժինը։"],
    ["Ի՞նչ կարող եմ անել վիրահատությունից առաջ ռիսկերը նվազեցնելու համար։", "Դադարեցրեք ալկոհոլն ու ծխելը, լոգանք ընդունեք վիրահատության նախորդ գիշերը եւ կատարեք վարժությունները։"],
    ["Իմ որ բժշկական խնդիրների համար պետք է տեսնեմ բժշկին։", "Բոլորի համար։"],
    ["Կպահանջվի՞ արյան փոխներարկում վիրահատության ընթացքում կամ հետո։ Կարելի՞ է պահել իմ արյունը նախապես։", "Մենք ավտո-փոխներարկում չենք անում։ Պետք է կապվել արյան բանկի հետ, երբ ձեզ խնդրեն արյուն կազմակերպել։"],
    ["Որքա՞ն կտեւի վիրահատությունը։", "Առաջնային վիրահատությունը մոտ մեկ ժամ եւ 30 րոպե է, իսկ վերավիրահատությունը մոտ երեք ժամ։ Հիվանդանոցում մնալը երկուից չորս օր է։"],
    ["Ինչ տեսակի անզգայացում է օգտագործվելու։ Կա՞ն տարբերակներ։", "Քննարկվում է անեսթեզիոլոգի հետ։"],
    ["Վիրահատությունից հետո շատ ցավ կունենա՞մ։", "Ցավ կլինի։"],
    ["Ի՞նչ կարվի ցավը թեթեւացնելու համար։", "Այո, իհարկե։"],
    ["Ե՞րբ կսկսեմ վեր կենալ եւ շարժվել։", "Վիրահատությունից հետո երկրորդ օրը։"],
    ["Ինչպե՞ս կգնամ զուգարան վիրահատությունից հետո։ Կունենա՞մ միզային կաթետեր։", "Ոչ, եթե վիրահատությունից հետո 8 ժամում չմիզեք։"],
    ["Հիվանդանոցում ֆիզիոթերապիա կունենա՞մ։", "Այո, մեկ սեանս վիրահատությունից հետո։"],
    ["Ինչ այլ բուժում կամ թերապիա կունենամ հիվանդանոցում։", "Ներերակային հակաբիոտիկներ եւ ցավազրկում։"],
    ["Որքա՞ն պետք է մնամ հիվանդանոցում։", "Երկուից չորս օր։"],
    ["Կկարողանա՞մ քայլել հիվանդանոցից դուրս գալիս։ Տուն կգնա՞մ, թե՞ այլ տեղ վերականգնվելու։", "Վիրահատության երկրորդ օրը տուն կգնաք քայլելով։ Կոնքի ամբողջական վիրահատության հիվանդները տուն կտեղափոխվեն շտապօգնությամբ։"],
    ["Պե՞տք է դադարեցնեմ որեւէ դեղ վիրահատությունից առաջ։", "Այո, հակամակարդիչներ եւ որոշ այլ դեղեր։ Խորհրդակցեք nurse manager-ի հետ գործը նշանակելիս։"]
  ]
};

function renderSourceFaqs(language) {
  const list = document.querySelector(".original-faq-list");
  const faqs = sourceFaqs[language] || sourceFaqs.en;
  if (!list) return;

  list.innerHTML = "";
  faqs.forEach(([question, answer], index) => {
    const details = document.createElement("details");
    if (index === 0) details.open = true;
    const summary = document.createElement("summary");
    const paragraph = document.createElement("p");
    summary.textContent = question;
    paragraph.textContent = answer;
    details.append(summary, paragraph);
    list.append(details);
  });
}

function setLanguage(language) {
  const dictionary = translations[language] || translations.en;
  let placeholderCount = 0;
  document.documentElement.lang = language;
  document.documentElement.dir = language === "ar" ? "rtl" : "ltr";

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.getAttribute("data-i18n");
    if (key && dictionary[key]) {
      node.textContent = dictionary[key];
      if (dictionary[key].includes("Placeholder:") || dictionary[key].includes("Լրացնել:") || dictionary[key].includes("عنصر مؤقت:")) {
        const text = dictionary[key];
        const marker = language === "ar" ? "عنصر مؤقت:" : language === "hy" ? "Լրացնել:" : "Placeholder:";
        const markerIndex = text.indexOf(marker);
        if (markerIndex >= 0) {
          placeholderCount += 1;
          const label = language === "ar" ? `عنصر مؤقت ${placeholderCount}: ` : language === "hy" ? `Լրացնել ${placeholderCount}: ` : `Placeholder ${placeholderCount}: `;
          const before = text.slice(0, markerIndex);
          const placeholder = text.slice(markerIndex + marker.length).trimStart();
          node.textContent = "";
          node.append(document.createTextNode(before));
          const highlight = document.createElement("span");
          highlight.className = "placeholder-note";
          highlight.textContent = `${label}${placeholder}`;
          node.append(highlight);
        }
      }
    }
  });

  languageButtons.forEach((button) => {
    const isActive = button.getAttribute("data-lang") === language;
    button.setAttribute("aria-pressed", String(isActive));
  });

  renderSourceFaqs(language);

}

if (navToggle && siteNav) {
  navToggle.addEventListener("click", () => {
    const isOpen = siteNav.classList.toggle("is-open");
    navToggle.setAttribute("aria-expanded", String(isOpen));
  });

  siteNav.addEventListener("click", (event) => {
    if (event.target instanceof HTMLAnchorElement) {
      siteNav.classList.remove("is-open");
      navToggle.setAttribute("aria-expanded", "false");
    }
  });
}

document.querySelectorAll('a[href^="#"]').forEach((anchor) => {
  anchor.addEventListener("click", (event) => {
    const target = document.querySelector(anchor.getAttribute("href"));
    if (!target) return;
    event.preventDefault();
    target.scrollIntoView({ behavior: "smooth", block: "start" });
  });
});

languageButtons.forEach((button) => {
  button.addEventListener("click", () => {
    setLanguage(button.getAttribute("data-lang") || "en");
  });
});

setLanguage("en");
